alibaba/loongcollector

README.md, docs/en/guides/README.md
=> polish docs

plugins/input/docker/logmeta/metric_docker_file.go, plugins/input/docker/rawstdout/input_docker_stdout.go, plugins/input/docker/stdout/input_docker_stdout.go
export container collect fields for ilogtail-trace component
=> export container collect fields

CHANGELOG.md, plugins/processor/regex/regex.go, plugins/processor/regex/regex_benchmark_test.go, plugins/processor/regex/regex_test.go
fixed processor_regex not support  regular expression
https://github.com/alibaba/ilogtail/issues/8
=> fixed processor_regex not support  regular expression

CHANGELOG.md, plugins/input/kubernetesmeta/input_kubernetes_meta.go, plugins/input/kubernetesmeta/kubernetes_collect.go, plugins/input/kubernetesmeta/kubernetes_collect_apps.go, plugins/input/kubernetesmeta/kubernetes_collect_batch.go, plugins/input/kubernetesmeta/kubernetes_collect_core.go, plugins/input/kubernetesmeta/kubernetes_collect_networking.go
remove global variables in kubernetes meta to avoid data race
=> remove global variables in kubernetes meta to avoid data race

CHANGELOG.md
=> 1.0.27 release

helper/docker_center.go
fix read static docker info without labels
=> fix read static docker info without labels

plugins/flusher/kafka/flusher_kafka.go
allow user  custom define hash key
=> support custom hash partition

.github/ISSUE_TEMPLATE/config.yml, .github/workflows/build.yaml, .github/workflows/e2e-core.yaml, .github/workflows/e2e.yaml, .github/workflows/static-check.yaml, Makefile, plugins/input/httpserver/input_http_server_test.go, plugins/input/process/input_process_linux_test.go, plugins/input/syslog/parser_test.go, plugins/input/syslog/syslog.go, plugins/input/syslog/syslog_test.go, plugins/processor/addfields/processor_add_fields_test.go, plugins/processor/strptime/strptime_test.go, test/engine/boot/compose_test.go, test/engine/validator/sys_docker_profile_test.go
add unit test and e2e test CI process
=> add unit test and e2e test CI process

CHANGELOG.md, changes/v1.0.27.md, changes/v1.0.28.md, docs/en/guides/How-to-release.md, docs/zh/guides/How-to-release.md, scripts/generate-release-makedown.sh
add release markdown scripts and doc
=> add release markdown scripts and doc

CHANGELOG.md, changes/v1.0.29.md
=> v1.0.29 release

CHANGELOG.md, plugins/input/process/input_process.go, plugins/input/process/input_process_cache_linux.go
=> polish process plugin for threadNum and fdNum

pluginmanager/logstore_config.go, pluginmanager/logstore_config_test.go, plugins/input/docker/stdout/docker_stdout_processor_test.go
fix wrong sequence when processing raw log tags
=> fix-process-raw-log-tag-sequence

CHANGELOG.md, README-cn.md, docs/zh/usecases/How-to-use-telegraf-receiver.md, docs/zh/usecases/README.md
=> add-telegraf-usecase-doc

changes/v1.0.33.md
fix containerd fd not release problem
=> release v1.0.33

changes/v1.0.33.md
=> Release 1.0.33

CHANGELOG.md, plugins/input/kubernetesmeta/kubernetes_collect.go, plugins/input/kubernetesmeta/kubernetes_collect_core.go, plugins/input/kubernetesmeta/kubernetes_collect_core_test.go
add workload attribute of Pod meta in metric_meta_kubernetes
=> add-workload-for-kubernets-meta

CHANGELOG.md, helper/docker_center.go, helper/docker_cri_adapter.go
fix cri update without sandbox bug
=> fix cri update without sandbox bug

CHANGELOG.md, helper/log_file_reader.go, helper/service_helper.go, pkg/util/alarm.go, pluginmanager/global_config.go, pluginmanager/self_telemetry_alarm.go, plugins/input/docker/stdout/input_docker_stdout.go, plugins/input/telegraf/input_telegraf.go, plugins/input/telegraf/local_test/telegrafd, plugins/input/telegraf/telegraf_log_collector.go, plugins/input/telegraf/telegraf_log_collector_test.go, plugins/input/telegraf/telegraf_log_file_processor.go, plugins/input/telegraf/telegraf_manager.go, plugins/input/telegraf/telegraf_manager_test.go, vendor/github.com/alibaba/ilogtail/pkg/util/alarm.go
Collect the Telegraf log when the service_telegraf plugin works.
=> Add telegraf monitor

.gitignore, plugins/input/mysql/mysql.go
* add err log of mysql query 
* add bin/ to .gitignore
=> add err log for mysql collect

CHANGELOG.md, Makefile, test/engine/validator/sys_docker_profile_test.go
=> fix ci unit tests

docs/en/guides/How-to-write-flusher-plugins.md, docs/zh/guides/How-to-write-flusher-plugins.md
=> chore: update fluster plugin doc format

.dockerignore, Makefile, core/app_config/AppConfigBase.cpp, core/app_config/AppConfigBase.h, core/config_manager/ConfigManagerBase.h, core/logtail_windows.cpp, docker/Dockerfile_production
=> Fix container image cannot collect files

core/config_manager/ConfigYamlToJson.cpp
=> fix backward compatibility problem for docker file

core/processor/LogProcess.cpp
=> change s_processBytes type from int to long

CHANGELOG.md, core/common/LogtailCommonFlags.h, core/config_manager/ConfigManager.cpp, core/config_manager/ConfigManager.h, core/config_manager/ConfigManagerBase.cpp, core/config_manager/ConfigManagerBase.h, docs/cn/configuration/collection-config.md, docs/cn/configuration/system-config.md
=> add support for hot reloading

docker/Dockerfile_development_part
=> change libebpf region

core/common/DynamicLibHelper.cpp, core/common/DynamicLibHelper.h, core/observer/metas/ConnectionMetaManager.cpp, core/observer/network/NetworkObserver.cpp, core/unittest/observer/NetLinkUnittest.cpp, test/case/behavior/input_observer_http/mock/main.go
glibc compatibility for kernel 2.x
=> glibc compatibility for kernel 2.x

core/logtail_windows.cpp
=> Revert "rm windows"

core/plugin/LogtailRuntimePlugin.cpp
[Issue opened here](https://github.com/alibaba/ilogtail/issues/340)
=> 【BUG】fix ptr mismatch

.github/workflows/build-pure-plugin.yaml, scripts/gen_build_scripts.sh
=> [fix] fix out of memory compile error

docs/cn/SUMMARY.md, docs/cn/data-pipeline/input/service-gpu.md, docs/cn/data-pipeline/overview.md
=> add-gpu-docs

core/event_handler/EventHandler.cpp, core/reader/LogFileReader.cpp, core/reader/LogFileReader.h
=> force close fd after timeout for deleted files

helper/docker_center.go, helper/k8s.go, helper/k8s_test.go, plugins/input/jmxfetch/jmxfetch.go, scripts/plugin_build.sh
=> polish jmxfetch

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
=> fix devcontainer permission

core/plugin/LogtailPlugin.cpp
fix code merge error here https://github.com/alibaba/ilogtail/pull/196/files#diff-bf01a1b8ff3cb1b55f2f82574df6ecad5edd2f1f6080ea01afe68ba6eab2acec
=> [fix] plugin load

docs/cn/data-pipeline/input/service-mssql.md, docs/cn/data-pipeline/input/service-pgsql.md
=> fix mssql & pgsql title

docs/cn/data-pipeline/flusher/otlp-log.md, helper/grpc_helper.go, plugins/flusher/otlplog/flusher_otlp_log.go, plugins/flusher/otlplog/flusher_otlp_log_test.go, vendor/github.com/alibaba/ilogtail/pkg/protocol/converter/converter.go, vendor/github.com/alibaba/ilogtail/pkg/protocol/converter/custom_single_log.go, vendor/github.com/alibaba/ilogtail/pkg/protocol/converter/otlp_log.go
- support auto reconnect when grpc connection is not ready
=> feature: support auto reconnect when grpc connection is not ready

licenses/LICENSE-curl, licenses/LICENSE-japronto, licenses/LICENSE-journalbeat, licenses/LICENSE-kubernetes, licenses/LICENSE-telegraf, tests/ilogtail/checkpoint/logtail_check_point
需要添加license声明的文件
1. curl  `core/sdk/CurlAsynInstance.cpp`
2. japronto `core/common/protocol/picohttpparser/picohttpparser.h`
3. journalbeat `plugins/input/journal/follow.go`
4. kubernetes `pkg/signals/signal.go` `pkg/signals/signal_posix.go` `pkg/signals/signal_windows.go`
5. telegraf `plugins/processor/grok/processor_grok_default_patterns.go` `plugins/input/nginx/input_nginx.go`
=> supplementary license statement for source code dependencies

docs/cn/data-pipeline/input/service-kafka.md, vendor/github.com/bsm/sarama-cluster/consumer.go
解决kafka_input 插件 无法commit问题
https://github.com/alibaba/ilogtail/issues/471
=> fix:kafka_input commit loop time

core/config_manager/ConfigManager.cpp
=> remove deleted handlers during config update

docs/cn/SUMMARY.md, docs/cn/data-pipeline/flusher/kafka.md, docs/cn/data-pipeline/flusher/kafka_v2.md, docs/cn/data-pipeline/input/input-docker-stdout.md, docs/cn/getting-started/k8s-daemonset-to-kafka.md, docs/cn/getting-started/k8slog-collect-to-sls.md, docs/cn/installation/start-with-k8s.md, example_config/start_with_k8s/ilogtail-daemonset.yaml, k8s_templates/ilogtail-daemonset-file-to-kafka.yaml, k8s_templates/ilogtail-daemonset-file-to-sls.yaml, k8s_templates/ilogtail-daemonset-stdout-to-kafka.yaml, k8s_templates/ilogtail-daemonset-stdout-to-sls.yaml
For pods using hostNetwork, their dnsPolicy should be set to "ClusterFirstWithHostNet"
fix: https://github.com/alibaba/ilogtail/issues/545
=> fix: Incorrect dnsPolicy setting in ilogtail-daemonset.yaml

Makefile, changes/v1.3.1.md, core/CMakeLists.txt, core/app_config/AppConfigBase.cpp, core/common/MachineInfoUtil.cpp, docker/Dockerfile_build, docker/Dockerfile_development_part, docker/Dockerfile_production, docs/cn/data-pipeline/processor/processor-desensitize.md, docs/cn/installation/release-notes.md, docs/en/guides/How-to-build-with-docker.md, docs/en/guides/How-to-do-manual-test.md, plugin_main/wrapmemcpy/wrap_memcpy.go, plugin_main/wrapmemcpy/wrap_memcpy.h, plugin_main/wrapmemcpy/wrap_memcpy_others.go, plugins/processor/desensitize/processor_desensitize.go, plugins/processor/desensitize/processor_desensitize_test.go, scripts/docker_build.sh, scripts/gen_build_scripts.sh, scripts/plugin_build.sh, scripts/plugin_gocbuild.sh, test/engine/boot/compose.go
1. Get Host IP returns wrong IP
2. ARM version cannot run on Ubuntu 20.04
3. Send buffer path env and config not match
=> fix 3 bugs in v1.3.0

docs/cn/config-server/quick-start.md
Add doc on how to configure ConfigServer at Agent
=> doc: configserver

CHANGELOG.md, helper/docker_center.go, helper/envconfig/aliyunlog_operation_wrapper.go, pkg/util/container_config.go, pluginmanager/global_config.go, pluginmanager/plugin_manager.go, plugins/input/docker/logmeta/metric_docker_file.go, plugins/input/docker/stdout/input_docker_stdout.go
=> Add logs for container matching in stdout plugin

CHANGELOG.md, external/github.com/aliyun/alibaba-cloud-sdk-go/services/sls_inner/analyze_product_log.go, helper/envconfig/aliyun_log_config_define.go, helper/envconfig/aliyunlog_operation_wrapper.go, helper/envconfig/product_api.go
=> add more env field

core/app_config/AppConfig.cpp
=> compatible to windows compile

scripts/e2e.sh, tools/builder/config.go
由于Github 镜像变更导致ebpf e2e失效，且github runner不支持指定版本镜像，暂时跳过ebpf e2e
=> Polish ebpf e2e test

docs/cn/developer-guide/data-model.md, go.mod, pkg/models/common.go, pkg/models/factory.go, pkg/models/logs.go, pkg/protocol/converter/otlp_test.go, pkg/protocol/decoder/opentelemetry/decoder_test.go, pkg/util/string_helper.go, pkg/util/string_helper_test.go, pluginmanager/plugin_runner_v2.go, plugins/processor/split/logstring/split_log_string.go
对Log模型的修改，移动 Body 字段到 LogContent 中
=> feat: move Log Body to LogContent

helper/envconfig/aliyun_log_config_define.go
Considering increasing this limit, updated the boud
=> [FIX] update upperbound of autosplit

helper/envconfig/aliyunlog_operation_wrapper.go
Fix index when creating logstore in query mode
=> fix: close #798, fix index when creating logstore in query mode

plugins/input/netping/netping.go
https://github.com/alibaba/ilogtail/issues/808
=> ping add local mode support

docs/cn/SUMMARY.md, docs/cn/data-pipeline/overview.md, docs/cn/data-pipeline/processor/processor-gotime.md, docs/en/plugins/processor/processor_gotime.md, plugins/processor/gotime/processor_gotime.go, plugins/processor/gotime/processor_gotime_test.go
Fix: https://github.com/alibaba/ilogtail/issues/829
改动
* 将 SourceLocation 和 DestLocation 默认值更改为-100，表示未进行配置。
* 补充单元测试样例：sourceLocation 为空
* 根据[专业版文档](https://help.aliyun.com/document_detail/196161.html)编写中文文档，并翻译更新英文文档
=> fix: processor_gotime empty time zone

CHANGELOG.md, pkg/protocol/converter/custom_single_log.go, pkg/protocol/converter/custom_single_log_test.go
https://github.com/alibaba/ilogtail/discussions/847
1.fix json converter marshal without HTML escaped
=> json converter marshal without HTML escaped

tools/builder/main.go
- 构建过程中打印详细的gomod文件内容，便于确认引入的插件版本
=> feat: print imported plugin modules detail

go.mod, go.sum
https://github.com/iLogtail/VictoriaMetrics/commit/63406f1220b581964191ce2ac12c86e257700044
=> Add more prometheus service discovery support

docs/cn/data-pipeline/processor/processor-gotime.md
Fix: https://github.com/alibaba/ilogtail/issues/830
=> docs: explain processor_gotime time format

Makefile, pkg/helper/grpc_helper.go
fix the issue that gosec may fail when checking tls min version.
=> fix: gosec issue of tls version

docs/cn/data-pipeline/flusher/flusher-kafka_v2.md, docs/cn/data-pipeline/input/service-kafka.md
- Fix the description error of supported version range for Kafka
=> doc: fix document of flusher kafka v2

docs/cn/awesome-ilogtail/use-cases.md
=> doc: add use-case

docs/cn/data-pipeline/flusher/flusher-stdout.md, docs/cn/data-pipeline/processor/processor-default.md, docs/cn/data-pipeline/processor/processor-json.md, docs/cn/data-pipeline/processor/processor-rename.md, pkg/models/logs.go, plugins/flusher/stdout/flusher_stdout.go, plugins/input/debugfile/input_debug_file.go, plugins/processor/json/processor_json.go, plugins/processor/json/processor_json_test.go, plugins/processor/rename/processor_rename.go, plugins/processor/rename/processor_rename_test.go
=> add v2 interface to processor_json

example_config/user_contrib/linux-apache-errorlog.md
=> [example config]:add linux-apche-errorlog.md

example_config/user_contrib/vivado-synth-log.md
=> Add vivado_synth_log.md

example_config/user_contrib/linux-bash-dpkg.md
=> [example config] add linux-bash-dpkg.md

example_config/user_contrib/windows-logs-CBS.md
=> Example comfig

example_config/user_contrib/linux-kern-log.md
example_config for linux-kern-log
=> [example config] add linux-kern-log.md

config_server/service/test/interface_test.go, config_server/service/test/request.go
1. fix panic reported from #860
2. heartbeat request should carry config info
3. fix something about assertions
4. fix http method because comminucation protocol changed
=> fix config server unit test

CHANGELOG.md, docs/cn/data-pipeline/flusher/flusher-elasticsearch.md, plugins/flusher/elasticsearch/authentication.go, plugins/flusher/elasticsearch/flusher_elasticsearch.go, plugins/flusher/elasticsearch/flusher_elasticsearch_test.go
1. 使用 bulk 接口批量发送请求
2. 支持动态索引
3. 修复后端连接错误引起的 panic
4. 解藕 TLS 配置和 http 配置，修复只配置 http config 时的 panic
=> Elasticsearch flusher 新功能特性

CHANGELOG.md, plugins/input/goprofile/manager.go
fix service_go_profile nil panic
=> fix service_go_profile nil panic

.github/workflows/build-core.yaml, .github/workflows/build-pure-plugin.yaml, .github/workflows/build.yaml, .github/workflows/e2e-core.yaml, .github/workflows/e2e.yaml, .github/workflows/static-check.yaml
=> CI ignores the submission of static files

.github/workflows/build-core.yaml, .github/workflows/build-pure-plugin.yaml, .github/workflows/build.yaml, .github/workflows/e2e-core.yaml, .github/workflows/e2e.yaml, .github/workflows/static-check.yaml, core/event_handler/EventHandler.cpp
Update logreader_timeout_interval: 86400 * 30000 > INT32
Update workflow pull_request paths-ignore : add CHANGELOG.md, changes, licenses
=> Update logreader_timeout_interval and workflow

docs/cn/installation/start-with-k8s.md, scripts/ilogtail_control.sh
Refine the script to support adding startup parameters. such as 
**./ilogtail_control.sh start_and_block -enable_containerd_upper_dir_detect**
=> Refine the script to support adding startup parameters.

core/monitor/LogtaiMetric.cpp, core/monitor/LogtailMetric.h, core/monitor/MetricExportor.cpp, core/processor/Processor.h
1. 修复GetMetricsRecordRef直接返回实例，导致MetricsRecordRef对象被删除的问题
2. 增加了日志输出updateMetric的状态
3. 修复topic字段赋值问题
=> fix metrics

pluginmanager/plugin_runner_v2.go, pluginmanager/plugin_runner_v2_test.go, scripts/plugin_build.sh
1. do not copy libzstd if target already exists
2. support LDFLAGS when build go plugins
3. fix bug that extract tags error
=> fix: log model bug fix && build script optimize

.devcontainer/Dockerfile, docker/Dockerfile_build, docker/Dockerfile_development_part, docker/Dockerfile_goc
=> update build image 

plugins/flusher/elasticsearch/authentication.go
fix https://github.com/alibaba/ilogtail/issues/1157
=> elasticsearch flusher authentication fix tls config and http config

CHANGELOG.md, Makefile, changes/v1.8.0.md, changes/v1.8.1.md, core/CMakeLists.txt, docker/Dockerfile_build, docker/Dockerfile_development_part, docker/Dockerfile_production, docs/cn/installation/release-notes.md, docs/en/guides/How-to-build-with-docker.md, docs/en/guides/How-to-do-manual-test.md, scripts/docker_build.sh, scripts/gen_build_scripts.sh, scripts/plugin_build.sh, scripts/windows32_build.bat, scripts/windows64_build.bat, scripts/windows64_dist.bat, test/engine/boot/compose.go
=> merge 1.8.1 docs back 

CHANGELOG.md, Makefile, changes/v1.8.4.md, changes/v2.0.0.md, docker/Dockerfile_build, docker/Dockerfile_development_part, docker/Dockerfile_e2e, docker/Dockerfile_production, docs/cn/SUMMARY.md, docs/cn/installation/release-notes-1.md, docs/cn/installation/release-notes.md, docs/en/guides/How-to-build-with-docker.md, docs/en/guides/How-to-do-manual-test.md, scripts/docker_build.sh, scripts/gen_build_scripts.sh, scripts/plugin_build.sh, scripts/windows32_build.bat, scripts/windows64_build.bat, scripts/windows64_dist.bat, test/engine/boot/compose.go
=> bump version to 2.0.0 (#1318)

core/processor/daemon/LogProcess.cpp
=> fix: read length meta bug due to key typo

pluginmanager/logstore_config.go, plugins/flusher/stdout/flusher_stdout.go
1. 修复了不能正确识别插件配置文件global模块中pipeline版本的问题
2. 修复了日志最终输出时的一个格式问题
=> fix: correct pipeline version recognition issue

core/application/Application.cpp, core/processor/ProcessorFilterNative.cpp, core/processor/ProcessorParseApsaraNative.cpp, core/processor/ProcessorParseDelimiterNative.cpp, core/processor/ProcessorParseJsonNative.cpp, core/processor/ProcessorParseRegexNative.cpp, core/processor/ProcessorParseTimestampNative.cpp, core/processor/ProcessorSPL.cpp, core/processor/ProcessorSplitMultilineLogStringNative.cpp, core/unittest/models/CMakeLists.txt, core/unittest/models/EventGroupBenchmark.cpp
* improve worst case performance when all events failed to process
* Add benchmark
=> improve worst case performance when all events failed to process (#1465)

core/plugin/PluginRegistry.cpp, core/plugin/PluginRegistry.h, core/unittest/config/ConfigUnittest.cpp, core/unittest/plugin/PluginRegistryUnittest.cpp
core不再校验go插件名是否合法，让go plugin manager自行处理。
=> fix: no check go plugins in core

core/models/LogEvent.cpp, core/models/LogEvent.h, core/models/MetricEvent.cpp, core/models/MetricEvent.h, core/models/PipelineEvent.h, core/models/PipelineEventGroup.cpp, core/models/PipelineEventGroup.h, core/models/PipelineEventPtr.h, core/models/SpanEvent.cpp, core/models/SpanEvent.h, core/pipeline/Pipeline.cpp, core/unittest/models/PipelineEventGroupUnittest.cpp, core/unittest/models/PipelineEventPtrUnittest.cpp
支持同一个event group同时发往不同的flusher
=> support shallow copy for event group

core/parser/DelimiterModeFsmParser.cpp, core/parser/DelimiterModeFsmParser.h, core/processor/ProcessorParseDelimiterNative.cpp, core/reader/LogFileReader.cpp, core/reader/LogFileReader.h, core/unittest/processor/ProcessorParseDelimiterNativeUnittest.cpp
* fix delimiter parse double quote
* enable unittest coverage
* remove useless codes to improve unittest coverage
=> [backport] fix processor delimiter parse double quote (#1664) 

docs/cn/plugins/input/input-ebpf-file-security.md, docs/cn/plugins/input/input-ebpf-network-observer.md, docs/cn/plugins/input/input-ebpf-network-security.md, docs/cn/plugins/input/input-ebpf-process-security.md
modify status of ebpf input doc: Alpha -> Dev
=> fix ebpf input doc

docs/cn/plugins/flusher/flusher-http.md, go.mod, plugins/flusher/http/flusher_http.go, plugins/flusher/http/flusher_http_test.go, test/go.sum
1. \[ENHANCEMENT\]: 支持队列满丢弃，默认开启  
2. \[ENHANCEMENT\]: 支持发送前进行数据压缩[e.g. gzip, snappy]  
3. [ENHANCEMENT]: 集成ext_default_encoder，支持prometheus encoder [ 详见 #1665 ]
PS：1和2摘自 @shunjiazhu 的 [PR](https://github.com/alibaba/ilogtail/pull/1546)，后面的 flusher_prometheus 强依赖这2个特性
=> feat: enhance flusher_http, e.g. supporting prometheus encoder, snappy compression, etc.

core/file_server/event_handler/LogInput.cpp
- 问题：启用full drain模式时，如果发生了配置变更，则会导致input线程卡死
- 原因：没有将配置变更和进程退出区分对待
- 影响范围：从功能加入1.8版本后就存在
=> fix deadlock in full drain mode on config update

core/application/Application.cpp, core/plugin/flusher/sls/FlusherSLS.cpp
This pull request includes several changes to the initialization and startup processes in the `Application` class and an update to the endpoint source type in the `FlusherSLS` class. The most important changes are listed below:
* [`core/application/Application.cpp`](diffhunk://#diff-134511857f78b25a8af9e2dac1e0d22cf83747e35fd6ccc0da91bf10035eeb5bR117): Added initialization of the enterprise configuration provider in the `Init` method.
* [`core/application/Application.cpp`](diffhunk://#diff-134511857f78b25a8af9e2dac1e0d22cf83747e35fd6ccc0da91bf10035eeb5bL225-R226): Moved the initialization of the enterprise configuration provider from the `Start` method to the `Init` method and replaced it with a call to the `Start` method.
* [`core/plugin/flusher/sls/FlusherSLS.cpp`](diffhunk://#diff-608e4 …
=> Changed the endpoint source type from `LOCAL` to `REMOTE` in the `Init` method of `FlusherSLS`.

README.md
=> Update README.md rename to LoongCollector

docs/cn/plugins/input/service-otlp.md, pkg/protocol/decoder/opentelemetry/otlpDataToSLSProto.go, plugins/input/opentelemetry/service_otlp_v1_test.go
* enable otlp trace to SlsPb
* fix UT
=> [backport 2.0] Enable OTLP Trace flushing to SLS (#1906)

docs/cn/installation/quick-start.md
修复 YAML 语法错误，否则会导致采集配置文件解析报错
```
[2024-12-25 16:17:15.023687] [warning] [46905] /src/core/config/ConfigUtil.cpp:47 config file format error:skip current object error msg:parse yaml failed: yaml-cpp: error at line 4, column 5: end of map not found filepath:"/root/loongcollector/output/conf/continuous_pipeline_config/local/file_simple.yaml"
```
=> Fix yaml lint error

plugins/flusher/opentelemetry/flusher_otlp.go
This pull request is trying to fix #2011
=> flusher_otlp: Ensure headers are correctly passed when sending data

core/common/LogtailCommonFlags.cpp, core/common/LogtailCommonFlags.h, core/go_pipeline/LogtailPlugin.cpp, core/logtail.cpp, core/logtail_windows.cpp, docs/cn/installation/start-with-k8s.md, pkg/config/global_config.go, pkg/flags/flags.go, pkg/helper/docker_cri_adapter.go, plugins/input/netping/netping_test.go
This pr is used to close [issue 2031](https://github.com/alibaba/loongcollector/issues/2031)
=> [backport 1.8]fix EnableContainerdUpperDirDetect not effective

core/common/LogtailCommonFlags.cpp, core/go_pipeline/LogtailPlugin.cpp, core/logtail.cpp, core/logtail_windows.cpp, docs/cn/installation/start-with-k8s.md, pkg/config/global_config.go, pkg/flags/flags.go, pkg/helper/docker_cri_adapter.go, plugins/input/netping/netping_test.go
* fix EnableContainerdUpperDirDetect not effective
* chore format golang source code using gofmt
* chore add more error msg in netping unit test
* chore change invalid unit test content in netping unit test
---------
=> [backport 2.1] fix EnableContainerdUpperDirDetect not effective

core/app_config/AppConfig.cpp, core/app_config/AppConfig.h, core/application/Application.cpp, core/go_pipeline/LogtailPlugin.cpp, core/plugin/processor/inner/ProcessorTagNative.cpp, core/unittest/common/http/CurlUnittest.cpp, pkg/config/global_config.go, pkg/helper/dumper.go, pkg/helper/dumper_test.go, pkg/logger/logger.go, pkg/logger/logger_test.go, plugin_main/plugin_export.go, pluginmanager/checkpoint_manager.go, pluginmanager/checkpoint_manager_test.go, pluginmanager/file_config.go, pluginmanager/file_config_test.go, pluginmanager/plugin_manager.go, pluginmanager/plugin_runner_v1.go, pluginmanager/plugin_runner_v2.go, pluginmanager/processor_tag.go, pluginmanager/processor_tag_helper.go, pluginmanager/processor_tag_test.go, plugins/input/command/input_command.go, plugins/input/jmxfetch/jmxfetch.go, plugins/input/prometheus/input_prometheus.go, plugins/input/telegraf/input_telegraf.go, scripts/plugin_build.sh
Go流水线支持后台Goroutine，从文件中获取数据，并通过double buffer缓存数据：
1. File Tag
2. Host ID
=> feat: go pipeline support file tag and host id

config_server/protocol/README.md
页面跳转为 https://github.com/alibaba/loongcollector/discussions/404 ，修改链接地址
=> Fix links in config_server/protocol/README.md

README.md, config_server/protocol/v2/README.md, docs/cn/README.md, docs/cn/benchmark/performance-compare-with-filebeat.md, docs/en/guides/How-to-release.md
Update links in README.md, alibaba/ilogtail to alibaba/loongcollector
=> Update links in README.md

pkg/helper/collector_imp.go, pluginmanager/plugin_runner_v2.go, plugins/aggregator/baseagg/aggregator_base_test.go, plugins/aggregator/context/aggregator_context_test.go, plugins/aggregator/metadatagroup/aggregator_metadata_group_test.go, plugins/flusher/opentelemetry/flusher_otlp_test.go, plugins/input/httpserver/input_http_server_test.go, plugins/input/kafka/input_kafka_test.go, plugins/input/opentelemetry/service_otlp_test.go, plugins/processor/rename/processor_rename_test.go, scripts/check_glibc.sh, scripts/dist.sh, scripts/docker_build.sh, tools/coverage-diff/main.py
=> Fix class name NewObservePipelineConext typos 

core/checkpoint/CheckPointManager.cpp, core/checkpoint/CheckPointManager.h, core/config_manager/ConfigManager.cpp, core/controller/EventDispatcher.cpp, core/controller/EventDispatcher.h, core/event/Event.h, core/event_handler/EventHandler.cpp, core/event_handler/EventHandler.h, core/event_handler/LogInput.cpp, core/file_server/ContainerInfo.h, core/file_server/FileDiscoveryOptions.cpp, core/reader/LogFileReader.cpp, core/reader/LogFileReader.h, core/unittest/controller/EventDispatcherDirUnittest.cpp, core/unittest/event_handler/CMakeLists.txt, core/unittest/event_handler/CreateModifyHandlerUnittest.cpp, core/unittest/event_handler/ModifyHandlerUnittest.cpp
重点需要review一下 core/reader/LogFileReader.cpp
=> [backport] fix: collect files in PV when another container restart or stop

core/plugin/processor/ProcessorFilterNative.cpp, core/unittest/processor/ProcessorFilterNativeUnittest.cpp
与1.x系列兼容，允许过滤插件只配DiscardingNonUtf8这个参数
=> allow discardingnonutf8 in filter plugin for backward compatability

.gitignore, dev/bench/record.html, dev/bench/statistic.html
修改前后对比。
* 旧LoongCollector（Max和Avg不在一起，不太好比较）
* 新LoongCollector
* 旧多Agent（未居中，报表较小，不能下载数据）
* 新多Agent
=> update benchmark graphs

.github/workflows/benchmark.yaml, docs/cn/README.md, test/benchmark/test_cases/performance_file_to_blackhole_filebeat/case.feature, test/benchmark/test_cases/performance_file_to_blackhole_fluentbit/case.feature, test/benchmark/test_cases/performance_file_to_blackhole_loongcollector/case.feature, test/benchmark/test_cases/performance_file_to_blackhole_loongcollectorspl/case.feature, test/benchmark/test_cases/performance_file_to_blackhole_vector/case.feature, test/benchmark/test_cases/performance_file_to_file_filebeat/case.feature, test/benchmark/test_cases/performance_file_to_file_filebeat/docker-compose.yaml, test/benchmark/test_cases/performance_file_to_file_filebeat/filebeat.yml, test/benchmark/test_cases/performance_file_to_file_fluentbit/case.feature, test/benchmark/test_cases/performance_file_to_file_fluentbit/clear_files.sh, test/benchmark/test_cases/performance_file_to_file_fluentbit/docker-compose.yaml, test/benchmark/test_cases/performance_file_to_file_fluentbit/main.conf, test/benchmark/test_cases/performance_file_to_file_fluentbit/parsers.conf, test/benchmark/test_cases/performance_file_to_file_loongcollector/case.feature, test/benchmark/test_cases/performance_file_to_file_loongcollector/docker-compose.yaml, test/benchmark/test_cases/performance_file_to_file_loongcollector/loongcollector.yaml, test/benchmark/test_cases/performance_file_to_file_loongcollectorcgo/case.feature, test/benchmark/test_cases/performance_file_to_file_loongcollectorcgo/docker-compose.yaml, test/benchmark/test_cases/performance_file_to_file_loongcollectorcgo/loongcollector.yaml, test/benchmark/test_cases/performance_file_to_file_loongcollectorspl/case.feature, test/benchmark/test_cases/performance_file_to_file_loongcollectorspl/docker-compose.yaml, test/benchmark/test_cases/performance_file_to_file_loongcollectorspl/loongcollector.yaml, test/benchmark/test_cases/performance_file_to_file_vector/case.feature, test/benchmark/test_cases/performance_file_to_file_vector/clear_files.sh, test/benchmark/test_cases/performance_file_to_file_vector/docker-compose.yaml, test/benchmark/test_cases/performance_file_to_file_vector/vector.yaml
=> Add file-to-file benchmark test

.github/workflows/benchmark.yaml, Makefile, docker/Dockerfile_edge_linux, scripts/build_edge_linux.sh, scripts/docker_build.sh
成品镜像从1.2G降低到300M左右，另外edge版本支持了arm64镜像
=> Edge version support arm64 & Reduce the size of the final image

.github/workflows/static-check.yaml, core/host_monitor/collector/MetricCalculate.h, core/host_monitor/common/FieldEntry.h, core/unittest/host_monitor/CMakeLists.txt, core/unittest/host_monitor/MetricCalculateUnittest.cpp
新增计算指标min、max、avg的抽象类，主机监控指标都可以使用这个抽象类进行计算。
=> feat: add  metric calculate into host_monitor

pkg/flags/flags.go, plugins/input/journal/input_journal.go, plugins/input/kubernetesmetav2/meta_collector.go, plugins/input/kubernetesmetav2/meta_collector_const.go, plugins/input/kubernetesmetav2/meta_collector_test.go, plugins/input/kubernetesmetav2/service_meta.go
- update k8s domain configuration
-  add  cluster entity upsert logic
-  fix journal tail mode on Ubuntu
=> update k8s domain configuration, add  cluster entity upsert logic, fix journal tail mode on Ubuntu

plugins/flusher/kafkav2/flusher_kafka_v2.go
=> fix: HashKeys are not used when converting data (#2311)

plugin_main/plugin_export.go
Change-Id: I201090efbcacf0d4becf8cc614494575f9e87ce6
=> fix:  potenial zoombie cgo objects risk on windows platform

core/host_monitor/LinuxSystemInterface.cpp, core/host_monitor/collector/CPUCollector.cpp, core/host_monitor/collector/CPUCollector.h, core/unittest/host_monitor/CPUCollectorUnittest.cpp
=> feat: modify CPU collector
