alibaba/loongcollector

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/gen_env.sh
- Makefile
- docker/Dockerfile.ilogtail-build-linux-amd64
- docker/Dockerfile.ilogtail-build-linux-arm64
- docker/Dockerfile.ilogtail-toolchain-linux-amd64
- docker/Dockerfile.ilogtail-toolchain-linux-arm64
- docker/Dockerfile_build
- docker/Dockerfile_development_part
- docker/Dockerfile_goc
- docker/Dockerfile_production
- docker/build-mono-arch-build-image.sh
- scripts/dist.sh
- scripts/docker_build.sh
- scripts/download_ebpflib.sh
- scripts/gen_build_scripts.sh
- scripts/upgrade_adapter_lib.sh
Resolves:
1. some building system requires no root user
2. do not pollute the host's filesystem with root-owned files when dev in container
3. auto choose nearest repository to get build image
4. auto choose nearest oss to get libebpf.so
> Make Docker build image nonroot

- helper/decoder/influxdb/decoder.go
- helper/decoder/influxdb/decoder_test.go
> feat: do not replace influxdb acceptable chars when FieldsExtend enabled

- helper/decoder/influxdb/decoder.go
- helper/decoder/influxdb/decoder_test.go
- pkg/protocol/converter/converter_metric.go
- pkg/protocol/converter/converter_metric_test.go
问题：
对于 influxdb 协议，当metric name本身就包含“:”时，如 metric name: a:b，field name: value，经过input后，会变为 __name__: a:b
在后续的flusher环节，当前的处理环节，会错误的识别为 metric name: a，field name: b
解决：
input_httpserver中，对于influxdb，添加一个__filed__字段，来记录真实的field，这样后续在还原的时候，便有了可靠的依据
__field__字段是否添加，也通过现有的FieldsExtend来控制
> fix: fix metric name field name split error when contains ":"

- docs/cn/data-pipeline/flusher/http.md
- docs/cn/developer-guide/log-protocol/README.md
- docs/cn/developer-guide/log-protocol/protocol-spec/raw.md
- helper/converter_helper.go
- pkg/protocol/converter/converter.go
- pkg/protocol/converter/converter_raw.go
- pkg/protocol/converter/converter_raw_test.go
- plugins/flusher/http/flusher_http.go
- plugins/flusher/http/flusher_http_test.go
add config item Convert.Separator for http flusher to support  multiple events splicing from one group in different scenarios
> feat: http flusher add Convert.Separator config field

- .devcontainer/Dockerfile
When groups with the same group_name or group_id exist in the docker environment, it causes the user added in a wrong group and  fail to get write permission of `/opt` directory.
> Fix user privilege problem in Developping-docker-env 

- Makefile
- scripts/docker_build.sh
1. enable docker buildkit only if both docker_version >= 19.03 && SSH_AUTH_SOCK env set
2. fix bug that fail to run docker_build.sh directly if SSH_AUTH_SOCK not set
reference: https://pythonspeed.com/articles/docker-buildkit/
> feat: check docker version to determine whether using docker buildkit

- core/event_handler/EventHandler.cpp
迭代器在 `++readerIter;` 继续使用，会造成内存访问错误。示例：
```
#include <iostream>
#include <vector>
int main() {
std::vector<int> myVector {1, 2, 3, 4, 5};
// 使用迭代器遍历 vector
for (auto it = myVector.begin(); it != myVector.end(); ) {
++it;
std::cout << *it << " ";
}
return 0;
}
```
实测：
> fix memory access error in evenv_handler

- plugins/processor/desensitize/processor_desensitize.go
- plugins/processor/desensitize/processor_desensitize_test.go
新旧对比
测试场景：password脱敏。使用regex匹配，const替换
goos: linux
goarch: amd64
pkg: github.com/alibaba/ilogtail/plugins/processor/desensitize
cpu: Intel(R) Xeon(R) Platinum 8369B CPU @ 2.70GHz
Case 1: content中有一处需要脱敏，处理时间减少55.60%，内存占用减少59.14%
Case 2: content中有两处需要脱敏，处理时间减少64.60%，内存占用减少64.82%
Case 3: content中有三处需要脱敏，处理时间减少70.85%，内存占用减少68.12%
Case 4: content中有10处需要脱敏，处理时间减少84.43%，内存占用减少78.09%
> Processor desensitize improve performance

- core/profiler/LogFileProfiler.cpp
之前profile的日志key为projectName + "_" + category + "_" + filename，如果用户有两个采集配置采集同一个文件，那么profile数据始终会显示第一个采集配置的名字，造成信息展示错误
> fix shennong log key

- pkg/helper/docker_center.go
- pkg/helper/docker_center_file_discover_test.go
- pkg/helper/docker_center_test.go
- pkg/helper/docker_cri_adapter.go
updateContainer原设计上不支持覆盖更新，只支持增量更新。
静态文件读取容器信息场景下，如果静态文件有变更，重复读取静态文件，会导致sandbox信息丢失。
> fix static container

- core/reader/LogFileReader.cpp
超长日志被截断可以分为两种情况：
* 单行：e.g. xxxxxx。
* 在 ReadUTF8 中，`moreData` 为 true，`nBytes` 为 0。
* 在 ReadGBK 中，`moreData` 为 true，`readCharCount` 为 0。
* 多行：e.g. Begin Reg\nxxxx\nxxxxx
* 在 ReadUTF8 中，`moreData` 为 true，`readCharCount` 为 0（因为之前的日志被 `LastMatchedLine` 截断了，因此，如果需要匹配BeginReg，那么一定是在开头，所以 `nBytes` 为 0。）
* 在 ReadGBK 中，`moreData` 为 true，`resultCharCount` 为 0。
> fix too long log split alarm

- core/reader/LogFileReader.cpp
- core/reader/LogFileReader.h
- core/unittest/reader/LogFileReaderUnittest.cpp
UTF8 和 GBK 编码中都存在多字节字符。当读取的日志超出 buffer size 的时候，日志就会被截断读取。这种情况下，就有可能导致多字节字符被 split 在两次读取，导致乱码。
在每次读取日志时，都会对读取的日志进行回退。所以，利用逆向回退，将读取的字符进行回退对齐。
> fix: multi-bytes character cut off

- plugins/flusher/http/flusher_http_test.go
删除重复的测试案例："Given a http flusher with empty converter"
> fix: remove duplicated http flusher test case

- pkg/protocol/converter/otlp.go
- pkg/protocol/converter/otlp_test.go
- Modify calculation of log record timestamp in "otlp.go" file to include nanoseconds
#1031
> fix: Improve accuracy of log record timestamps

- core/logger/Logger.cpp
- core/logger/Logger.h
#944 
如果在k8s中部署ilogtial并将`apsara_log_conf.json`文件挂载为`ConfigMap`，将导致无法创建snapshot目录。
这主要是因为原逻辑只要检测到 `apsara_log_conf.json`文件，并且配置文件中存在某些选项，就不会创建snapshot目录。现添加一个`CheckSnapshotDir()`函数，在读取`apsara_log_conf.json`文件成功后调用，主要判断snapshot目录是否存在，不存在就创建。
> 无法创建snapshot目录

- core/event_handler/EventHandler.cpp
目前，超过30天没有变化的文件，Reader会被删除，导致其下次有更新时会被认为是新文件。
因此存在一些更新间隔很长的日志文件，每次更新日志都会出现重复采集的问题。
本pr间接解除了超时删除Reader的逻辑来解决此问题
> Optimizing reader release strategy

- core/config/Config.cpp
- core/controller/EventDispatcherBase.cpp
- core/event_handler/EventHandler.cpp
- core/processor/LogProcess.cpp
- core/profiler/LogFileProfiler.cpp
- core/profiler/LogFileProfiler.h
- core/reader/DelimiterLogFileReader.cpp
- core/reader/DelimiterLogFileReader.h
- core/reader/JsonLogFileReader.cpp
- core/reader/JsonLogFileReader.h
- core/reader/LogFileReader.cpp
- core/reader/LogFileReader.h
- core/unittest/reader/DeletedFileUnittest.cpp
AddProfilingData使用的key是projectName + "_" + category + "_" + configName + "_" + filename
之前filename使用的是：std::string GetConvertedPath() const { return mDockerPath.empty() ? mLogPath : mDockerPath; }
容器场景下，比如用户配置的是容器内的，/home/log/123.log，GetConvertedPath返回的是/home/log/123.log，这样在容器重启之后，filename是不变的，导致统计的时候，上一个容器的统计仍在累加。
修改之后，filename使用的是mLogPath，为采集的真实路径，容器重启之后，AddProfilingData的key会变化，会重新统计
> fix profile file name in container

- plugins/input/opentelemetry/service_oltp.go
解决了：ilogtail 使用otlp插件 配置文件删除之后，插件还继续运行 #1030
> Fixed the abnormal shutdown issue of service_otlp

- CHANGELOG.md
- core/config_manager/ConfigManagerBase.cpp
- pkg/helper/container_config.go
- pkg/helper/container_export.go
- pkg/helper/docker_center.go
- pkg/helper/docker_center_test.go
- pluginmanager/container_config_manager.go
- pluginmanager/container_config_manager_test.go
- pluginmanager/plugin_manager.go
- pluginmanager/self_telemetry_container_config.go
- plugins/input/docker/logmeta/metric_docker_file.go
- plugins/input/docker/stdout/input_docker_stdout.go
主要优化点：
1. 增量/删除容器由各个采集diff计算，统一到一个线程里进行diff计算。由此原container_config.go里带锁的逻辑全部删除
2. 采集配置加载的时候，第一次一定上报采集配置结果，避免信息漏上报
3. 原来计时器逻辑删除，由self_telemetry_container_config.go触发定时逻辑
4. PluginStats中增加容器信息采集标志
> refine container info code

- pkg/helper/container_export.go
- pkg/helper/docker_center.go
目前基础环境为k8s+containerd的模式，查看logtail_plugin.LOG发现。即便不使用docker，也会初始化dockerClient,并且多次尝试连接，错误日志如下
```
2023-07-06 08:37:02 [INF] [plugin_manager.go:120] [Init] init plugin, local env tags:[_node_name_ ihuman _node_ip_ 10.2.112.25]
2023-07-06 08:37:02 [INF] [checkpoint_manager.go:96] [Init] init checkpoint:<nil>
2023-07-06 08:37:02 [INF] [logstore_config.go:666] [loadBuiltinConfig] load built-in config statistics, config name: shennong_log_profile, logstore: logtail_plugin_profile
2023-07-06 08:37:02 [INF] [logstore_config.go:666] [loadBuiltinConfig] load built-in config alarm, config name: logtail_alarm, logstore: logtail_alarm
2023-07-06 08:37:02 [INF] [logstore_config.go:666] [loadBuiltinConfig] load built-in config container, config name: logtail_containers, logstore: logtail_containers …
```
> add_dockerClient_conn_test

- core/app_config/AppConfig.cpp
- core/config_manager/ConfigManager.cpp
不再检查 ilogtail_config.json 文件的配置 ilogtail_configserver_address 参数中地址的合法性，不限制只能输入 IP，可以是域名或者主机名，如果连接报错，打印出错地址和端口
> fix: remove the ip restrict of config server address, allow domain and hostname

- core/controller/EventDispatcherBase.cpp
fix #1081, skip dev check to avoid duplicated data collection when run as statefulset sidecar
> fix #1081, skip dev check to avoid duplicated data collection when run as statefulset sidecar

- docs/cn/data-pipeline/flusher/flusher-kafka_v2.md
修改flusher_kafka_v2插件文档样例，里面flushers的Type字段描述有误
> 修改flusher_kafka_v2插件文档样例的错误描述

- config_server/service/.gitignore
- config_server/service/go.mod
- config_server/service/interface/agent/collection_config.go
- config_server/service/interface/agent/status.go
- config_server/service/interface/user/agent_group.go
- config_server/service/interface/user/collection_config.go
- config_server/service/manager/agent/agent_manager.go
- config_server/service/manager/agent/agent_operator.go
- config_server/service/manager/config/agent_operator.go
- config_server/service/manager/config/config_manager.go
- config_server/service/manager/config/user_operator.go
- config_server/service/manager/manager.go
- config_server/service/model/agent.go
- config_server/service/model/agent_group.go
- config_server/service/model/collection_config.go
- config_server/service/router/router.go
- config_server/service/service.go
- config_server/service/setting/setting.go
- config_server/service/store/interface_database/interface_database.go
- config_server/service/store/leveldb/leveldb.go
- config_server/service/store/store.go
- config_server/service/test/interface_test.go
- config_server/service/test/request.go
- config_server/service/test/setting_test.go
- config_server/service/test/store_test.go
去除对 github 仓库的依赖，方便用户对 ilogtail config server 进行二次开发
> config server import local packages instead of github project packages

- CHANGELOG.md
- core/common/StringTools.cpp
- core/common/StringTools.h
- core/logger/Logger.cpp
- core/logger/Logger.h
- docs/cn/configuration/system-config.md
- pkg/logger/logger.go
- pkg/logger/logger_test.go
fixes #959
- follow the issue, and make this pr.
- use devcontainer to develop, follow the article [here](https://mp.weixin.qq.com/s/o-cvM_0YGzv8UiMzls8OSg)
-  export LOGTAIL_LOG_LEVEL=debug
- ./ilogtail &
- see the log prints like below:
```
read log level from the env successfully, level: debug
Load log config from /root/go/src/github.com/ilogtail/core/build/apsara_log_conf.json
Logger size in config: 4
Path of logger named /: /workspaces/ilogtail/core/build/ilogtail.LOG
logger named / created.
Path of logger named /apsara/sls/ilogtail: /workspaces/ilogtail/core/build/ilogtail.LOG
logger named /apsara/sls/ilogtail created.
Path of logger named /apsara/sls/ilogtail/profile: /workspaces/ilogtail/core/build/snapshot/ilogtail_profile.LOG
logger named /apsara/sls/ilogtail/profile created. …
```
> [log parts enhance] Use env to control ilogtail log level 

- docs/cn/data-pipeline/flusher/flusher-http.md
- plugins/flusher/http/flusher_http.go
- plugins/flusher/http/flusher_http_test.go
优化flusher_http
1. 添加queue buffer，提高多个flusher_http的并发效率
2. 允许设置异步过滤数据
3. 当过滤后的数据event为空时直接返回
> feat: add flusher_http queue buffer and async interceptor settings

- pkg/helper/self_metric_imp.go
- pkg/helper/self_metric_imp_test.go
- plugins/input/canal/input_canal.go
- plugins/processor/encrypt/processor_encrypt.go
1. self_metric 支持创建时传入 labels，并且在Serialize时附加到 LogContents 种
2. 在Serialize时添加 `__name__` label ，该 label 在 convert 时使用
> feat: support labels for self_metric

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/devcontainer.json.lldb
* Development containers add additional plugins for using vscode GUI debugging functionality;
* Upgrade the glibc version for using the relevant vscode plugins.
> Enhancing the vscode development experience

- core/event/BlockEventManager.h
修复BlockedEvent在update的时候，非预期的事件覆盖行为
问题现象：
NAS场景Json采集，CP文件的方式替代历史文件采集的情况下，发现大量文件只采集了一小部分。
> fix: Correct premature file read termination triggered by sender back pressure

- core/common/JsonUtil.cpp
- core/config/Config.h
- core/processor/ProcessorParseApsaraNative.cpp
- core/processor/ProcessorParseApsaraNative.h
- core/unittest/processor/ProcessorDesensitizeNativeUnittest.cpp
- core/unittest/processor/ProcessorFilterNativeUnittest.cpp
- core/unittest/processor/ProcessorParseApsaraNativeUnittest.cpp
- core/unittest/processor/ProcessorParseDelimiterNativeUnittest.cpp
- core/unittest/processor/ProcessorParseJsonNativeUnittest.cpp
This commit addresses incorrect parsing outcomes in ProcessorParseApsaraNative when reading a large buffer that contains multiple log entries. New unit tests have been introduced for ProcessorParseApsaraNative, ProcessorParseDelimiterNative, and ProcessorParseJsonNative to verify accurate parsing of log data in scenarios involving large buffer inputs.
> fix: Correct parsing errors in ProcessorParseApsaraNative with large buffer input

- docs/cn/data-pipeline/flusher/flusher-http.md
- pkg/protocol/converter/converter.go
- pkg/protocol/converter/jsonline.go
- pkg/protocol/converter/jsonline_test.go
- plugins/flusher/http/flusher_http.go
This PR is to support [jsonline protocol](https://jsonlines.org/) which is supported by the [FluentBit collector](https://docs.fluentbit.io/manual/pipeline/outputs/http).
This could help ilogtail work with [VictoriaLogs](https://docs.victoriametrics.com/VictoriaLogs/), the newly released open-source log solution this year.
> Support jsonline protocol

- docs/cn/data-pipeline/flusher/loki.md
- pkg/protocol/converter/converter.go
- pkg/protocol/converter/converter_single_log_flatten.go
- plugins/flusher/loki/flusher_loki.go
Fix https://github.com/alibaba/ilogtail/issues/1020#issuecomment-1644906430
1. Add `ContentsOnly` option for loki flusher (currently only work for `custom_single_flatten` protocol)
2. Polish docs (Fix https://github.com/alibaba/ilogtail/issues/1020#issuecomment-1641556137)
> Support contents only for loki flusher

- core/parser/DelimiterModeFsmParser.cpp
- core/unittest/processor/ProcessorParseDelimiterNativeUnittest.cpp
The issue is resolved by correctly initialize fieldStart and fieldEnd variables in DelimiterModeFsmParser
> Fix delimiter parsing for logs with leading spaces

- core/parser/DelimiterModeFsmParser.cpp
- core/unittest/processor/ProcessorParseDelimiterNativeUnittest.cpp
The issue is resolved by correctly initialize fieldStart and fieldEnd variables in DelimiterModeFsmParser
> [backport]Fix delimiter parsing for logs with leading spaces

- core/processor/ProcessorParseApsaraNative.cpp
- core/processor/ProcessorParseTimestampNative.cpp
之前插件化的时候都改乱了，问题包括：
1. 飞天和时间解析插件丢弃历史日志的时间间隔不再是12小时，而是一个随时区变化的数字
2. 飞天的微妙调整无效，__time__时区错误
改动已通过回归测试
This commit resolves two timezone-related issues in iLogtail's native processors. Previously, ProcessorParseApsaraNative did not initialize the timezone option correctly, nor did it account for timezone settings when adjusting time. Additionally, ProcessorParseTimestampNative was incorrectly filtering timeout logs by subtracting the timezone offset twice.
Changes include:
- Correct initialization of the timezone option in ProcessorParseApsaraNative to ensure that log processing aligns with the configured timezone setting.
- Modification of time adjustment logic in ProcessorParseApsaraNative to correctly apply the timezone setting.
- Adjustment of the log filtering logic in …
> Fix timezone handling in native processors

- core/file_server/FileServer.cpp
For file log collection, if watched dirs are in NFS, chances are it will take long to complete dir registration. Since current checkpoint dump time is reset before dir registration, and checkpoint dump period is set to 1 min in k8s, chances are checkpoints are dumped and cleared immediately after dir registration with NFS, right before log reader status can be recovered from checkpoints, which fianlly leads to log duplication.
Therefore, we should reset dump time after dir registration.
> fix: reset checkpoint dump time after dir registration completes to avoid log duplication

- core/processor/ProcessorParseApsaraNative.cpp
- core/processor/ProcessorParseApsaraNative.h
- core/unittest/processor/ProcessorParseApsaraNativeUnittest.cpp
This commit addresses a compatibility issue with timestamp parsing in apsara logs by ilogtail. Previously, ilogtail enforced a strict time format of %Y-%m-%d %H:%M:%S.%f, which resulted in failures when encountering apsara logs formatted with %Y-%m-%d %H:%M:%S,%f.
The fix introduces a more flexible parsing logic that disregards the character immediately following %S, allowing the parser to correctly handle sub-second parts denoted by any character. This patch also ensures that ilogtail can successfully parse timestamps without failing when the sub-second part is absent.
> Fix timestamp parsing compatibility issue for apsara log

- pkg/util/net_helper.go
- plugins/input/goprofile/discovery_static.go
- plugins/input/jmxfetch/jmxfetch.go
This commit addresses the limitation within the logtail profile schema regarding the inability to include the actual local IP address using the goprofile plugin. When profiling, the collection of non-specific host addresses (e.g., 127.0.0.1, localhost, or 0.0.0.0) leads to confusion over multiple target identification. To resolve this, the goprofile plugin has been enhanced to recognize and replace these generic addresses with the real local IP address of the machine.
Changes include:
- Automatic substitution of custom label values that correspond to 127.0.0.1, localhost, or 0.0.0.0 with the machine's actual local IP address.
> Improve goprofile plugin to support real local IP inclusion

- core/processor/ProcessorParseJsonNative.cpp
- core/processor/ProcessorParseJsonNative.h
- core/unittest/processor/ProcessorParseJsonNativeUnittest.cpp
This commit resolves an issue in ParseJsonNativeProcessor where the original log content was unintentionally retained in the "content" field due to improper state management.
The processor incorrectly maintained a class-level state indicating whether the "content" key was overwritten during JSON parsing. While this state should be reset for each new log, it was persistently kept across logs. Consequently, if a JSON log contained a "content" key, the processor would mark the state as overwritten and not drop the "content" field in subsequent logs, leading to duplicated content.
To address this, the state tracking the "content" key overwrite is moved from class level to local level, ensuring it is reset at the start of each log parsing operation.
> [backport]Fix log content duplication in ParseJsonNativeProcessor

- core/controller/EventDispatcherBase.cpp
For file log collection, if watched dirs are in NFS, chances are it will take long to complete dir registration. Since current checkpoint dump time is reset before dir registration, and checkpoint dump period is set to 1 min in k8s, chances are checkpoints are dumped and cleared immediately after dir registration with NFS, right before log reader status can be recovered from checkpoints, which finally leads to log duplication.
Therefore, we should reset dump time after dir registration.
> [backport] fix: reset checkpoint dump time after dir registration completes to avoid log duplication

- core/processor/ProcessorParseDelimiterNative.cpp
- core/processor/ProcessorParseDelimiterNative.h
Memeber mDelimiterModeFsmParserPtr is a raw pointer. It is not released in destructor. This patch fixed it by using a smart pointer instead.
> [backport]fix memory leak in ProcessorParseDelimiterNative

- core/processor/ProcessorParseApsaraNative.cpp
- core/unittest/processor/ProcessorParseApsaraNativeUnittest.cpp
This commit addresses a compatibility issue with timestamp parsing in apsara logs by ilogtail. Previously, ilogtail enforced a strict time format of %Y-%m-%d %H:%M:%S.%f, which resulted in failures when encountering apsara logs formatted with %Y-%m-%d %H:%M:%S,%f.
The fix introduces a more flexible parsing logic that disregards the character immediately following %S, allowing the parser to correctly handle sub-second parts denoted by any character. This patch also ensures that ilogtail can successfully parse timestamps without failing when the sub-second part is absent.
> [backport]Fix timestamp parsing compatibility issue for apsara log #1285

- core/processor/ProcessorParseDelimiterNative.cpp
- core/processor/ProcessorParseDelimiterNative.h
Memeber mDelimiterModeFsmParserPtr is a raw pointer. It is not released in destructor. This patch fixed it by using a smart pointer instead.
> fix memory leak in ProcessorParseDelimiterNative

- core/processor/ProcessorFilterNative.h
- core/processor/ProcessorParseApsaraNative.cpp
- core/processor/ProcessorParseDelimiterNative.cpp
- core/processor/ProcessorParseJsonNative.cpp
- core/processor/ProcessorParseRegexNative.cpp
- core/unittest/processor/ProcessorParseApsaraNativeUnittest.cpp
- core/unittest/processor/ProcessorParseDelimiterNativeUnittest.cpp
- core/unittest/processor/ProcessorParseJsonNativeUnittest.cpp
- core/unittest/processor/ProcessorParseRegexNativeUnittest.cpp
Before, the native processors chose to keep both source key and __raw_log__ if parsing fails and keeping unmatched content is desired. Keeping unmatched content in __raw_log__ is to be compatible with older version.
Keeping unmatched content in the source key is convenient if one want data to fall through the next processor when the previous one fails and such behavior is consistent with the behavior of the Go plugin. However, this could result in a doubling of the data volume. As connecting multiple native parsers or connecting native parsers with Go processors is rare now, after this patch only __raw_log__ will be kept. If one want to process the data that previous native processor fails, __raw_log__ must be configured as the source_key in the next processor.
> Fix: remove content if native processor parse failed

- core/processor/ProcessorParseApsaraNative.cpp
- core/processor/ProcessorParseApsaraNative.h
This submission resolves an issue in ProcessorParseApsaraNative. mSourceKeyOverwritten is no longer needed, and a local variable sourceKeyOverwritten has been defined to prevent concurrency issues.
> Fix: Delete mSourceKeyOverwritten in processorParseApsaraNative to prevent concurrency issues.

- core/processor/ProcessorParseApsaraNative.cpp
- core/processor/ProcessorParseApsaraNative.h
- core/reader/SourceBuffer.h
- core/unittest/processor/LogFilterUnittest.cpp
- core/unittest/processor/ProcessorFilterNativeUnittest.cpp
- core/unittest/processor/ProcessorParseApsaraNativeUnittest.cpp
- core/unittest/processor/ProcessorParseTimestampNativeUnittest.cpp
The parser previously used microsecond incorrectly in the time cache. Now only the time in second is properly retrieved from the cache. And the microsecond part is always parsed from log timestamps.
Additionally, a bounds check has been added to prevent out-of-range array access, ensuring reliable operation.
> Fix microsecond handling in Apsara log parser

- core/application/Application.cpp
- core/dependencies.cmake
- core/pipeline/PipelineManager.cpp
During refactor, function DeleteHandlers() is altered so that only called during pipeline update, not on container update. This would lead to memory leak in k8s.
>  Fix memory leak by deleting unused log readers during container update

- core/aggregator/Aggregator.cpp
- core/processor/daemon/LogProcess.cpp
- core/processor/daemon/LogProcess.h
- core/sender/Sender.cpp
1. Fixed the issue where the logGroup pointer was not released when using Golang plugins. 
2. Increase alarm threshold and reduce 'package list interval' configuration to fix the alarm of LOG_GROUP_WAIT_TOO_LONG_ALARM in LOGSTORE mode.
> Fix log group memory leak when using Golang plugins and reduce alarm frequency in LOGSTORE send mode

- core/processor/ProcessorFilterNative.cpp
- core/processor/ProcessorFilterNative.h
- core/unittest/processor/ProcessorFilterNativeUnittest.cpp
- docs/cn/installation/release-notes.md
- docs/cn/plugins/processor/native/processor-filter-regex-native.md
Since same keys are allowed for filter function in old config, the map structure in processor_filter_regex_native is incompatable with that. Thus, we should maintain old param FilterKey and FilterRegex.
> fix: deprecate param Include in processor_filter_regex_native and add replacement instead

- docs/cn/plugins/input/input-file.md
用户手册中文本日志多行日志采集给的案例正则表达式错误，导致无法采集案例中的多行日志
> 用户手册中文本日志多行日志采集给的案例正则表达式错误

- core/models/LogEvent.cpp
- core/models/LogEvent.h
- core/processor/CommonParserOptions.cpp
- core/processor/ProcessorDesensitizeNative.cpp
- core/processor/ProcessorFilterNative.cpp
- core/processor/ProcessorFilterNative.h
- core/processor/ProcessorParseApsaraNative.cpp
- core/processor/ProcessorSplitLogStringNative.cpp
- core/processor/ProcessorSplitRegexNative.cpp
- core/processor/daemon/LogProcess.cpp
- core/unittest/models/LogEventUnittest.cpp
1. 使用vector保存KV，然后新增一个map建立key的索引；
2. 删除某个key时，将其从索引中删除，但是vector中保留KV，仅标记其为无效
3. 遍历content时，实际遍历vector，但是需要跳过无效元素。
> fix: maintain sequential info of the original log content and allow multivalue for single key for apsara processor

- core/aggregator/Aggregator.cpp
- core/application/Application.h
- core/common/LogtailCommonFlags.cpp
- core/common/LogtailCommonFlags.h
- core/controller/EventDispatcher.cpp
- core/controller/EventDispatcher.h
- core/event_handler/EventHandler.cpp
- core/event_handler/EventHandler.h
- core/event_handler/LogInput.cpp
- core/event_handler/LogInput.h
- core/pipeline/PipelineManager.cpp
- core/sender/Sender.cpp
Introducing the full_drain_mode configuration, which when enabled, triggers a comprehensive data flush across the network during the shutdown sequence. This mode is particularly beneficial for environments with sidecar and fat containers where data persistence is not guaranteed post-application exit. By ensuring all data is transmitted prior to shutdown, we prevent potential data loss that could occur with local dumps, making this feature a critical addition for systems that require high data integrity and resilience.
> feat: add full_drain_mode option to ensure complete data flush over network before shutdown

- pkg/helper/docker_cri_adapter.go
Docker and containerd may co-exist in some cases. So if dockershim.sock exist, the CRI runtime may still valid.
> fix dockershim cause containerd invalid

- pkg/helper/docker_cri_adapter.go
Docker and containerd may co-exist in some cases. So if dockershim.sock exist, the CRI runtime may still valid.
> [backport] fix dockershim cause containerd invalid

- core/event_handler/EventHandler.cpp
- core/reader/LogFileReader.cpp
- test/case/behavior/reader_deleted/ilogtail-e2e.yaml
- test/case/behavior/reader_deleted/run.sh
- test/case/behavior/reader_log_rotate/ilogtail-e2e.yaml
- test/case/behavior/reader_log_rotate/run.sh
- 问题：
reader队列只有一个reader的时候，如果delete flag为true且已经读到尾巴了，会强制将最后不完整的日志发送出去。因为delete flag只是个hint，所以可能导致日志被截断。
- 修复：
对于上述情况，等待超时事件发生才flush。
> wait for read flush timeout instead of flushing last line immediately on file deletion

- core/go_pipeline/LogtailPlugin.cpp
- core/go_pipeline/LogtailPlugin.h
- pkg/config/config.go
- pkg/context.go
- pluginmanager/checkpoint_manager.go
- pluginmanager/context_imp.go
- pluginmanager/logstore_config.go
use config name with seq only in pluginmanager.LogtailConfig
>  ensure config name in golang config and ctx matching C++ config name

- core/logger/Logger.cpp
https://github.com/alibaba/ilogtail/pull/1096/files introduced a feature to adjust log level easily through env variable. This fix ensures that the log level for ilogtail.LOG is now properly set in accordance with the LOGTAIL_LOG_LEVEL value.
> fix: make LOGTAIL_LOG_LEVEL env variable effective for ilogtail.LOG

- core/application/Application.cpp
- core/monitor/LogtailAlarm.cpp
- core/sender/Sender.h
Alarms generated by the collector during the data collection process for profile 
projects were previously not reported due to a rule designed to prevent circular 
reporting of alarms. This rule intended to avoid alarms raised as a result 
of attempting to send alarms to the profile project. However, it inadvertently 
blocked genuine alarms that occurred during the direct collection to the profile 
project itself. This fix adjusts the rule to differentiate between circular 
alarms and legitimate collection errors, allowing the latter to be reported 
as expected.
> fix: Ensure alarms raised during collection for profile projects are reported

- core/common/FileSystemUtil.cpp
- core/config_manager/ConfigManagerBase.cpp
- core/unittest/common/FileSystemUtilUnittest.h
The precondition of ConfigManagerBase::RegisterWildcardPath is that the input path is normalized. Otherwise the index out of range may raise at runtime.
> fix: normalize logpath to avoid crash during handler registration

- core/common/CMakeLists.txt
- core/common/EncodingConverter.h
- core/common/memory/SourceBuffer.h
- core/models/PipelineEvent.h
- core/models/PipelineEventGroup.h
- core/monitor/LogIntegrity.h
- core/processor/daemon/LogProcess.cpp
- core/reader/LogFileReader.cpp
- core/reader/LogFileReader.h
- core/unittest/reader/LogFileReaderUnittest.cpp
- core/unittest/reader/RemoveLastIncompleteLogUnittest.cpp
1. 允许SourceBuffer被移动
2. 调整SourceBuffer.h文件位置
3. LogBuffer与SourceBuffer的关系从继承改成组合，主要便于组装PipelineEventGroup（只需要SourceBuffer，不需要LogBuffer）
> refactory: enable move for SourceBuffer

- docs/cn/configuration/collection-config.md
- docs/cn/plugins/flusher/flusher-pulsar.md
1、Fix the errors in the Pulsar Flusher documentation.
2、Add a configuration description for EnableTimestampNanosecond in the plugin's global settings.
> document: fix document for flusher pulsar

- pkg/helper/docker_center.go
- pkg/helper/docker_cri_adapter.go
问题背景：
在当前的容器发现机制中，尽管fetchone流程会暂时保留已经退出的容器信息一定时间（即ContainerInfoDeletedTimeout设定的时长），FetchAll流程却不会包含已经退出的容器，并且FetchAll会按定时计划执行。这种设计可能导致FetchAll提前清除已退出的容器，使得相关容器日志未能被有效采集。
修复措施：
我们对FetchAll流程做了改进，从现在起它会检查容器退出的时间是否没有超过ContainerInfoDeletedTimeout设定的阈值。只要没有超过这个时间限制，即便容器已退出，它仍会被FetchAll加以考虑。此外，我们提升了ContainerInfoDeletedTimeout的值至120秒，这一改进增加了日志采集的完成率和成功性。
> Improved container discovery mechanism for collecting logs from exited containers in a timely manner.

- pluginmanager/always_online_manager.go
- pluginmanager/always_online_manager_test.go
- pluginmanager/logstore_config.go
- pluginmanager/plugin_manager.go
- 问题：配置变更依然会导致stdout重复采集
- 原因：之前调整Go的真假配置名仍然存在疏漏，只关注了LogtailConfig这个全局结构，忽略了LastLogtailConfig、DisabledLogtailConfig和AlwaysOnlineManager里的配置名也应该是带后缀的。
- 修复：在logstoreConfig里保留带后缀的配置名，在timeoutstop的时候需要使用。
> fix go checkpoint deletion problem caused by always online config mistaken for deleted

- core/common/YamlUtil.cpp
- core/common/YamlUtil.h
- core/unittest/common/YamlUtilUnittest.cpp
解决配置yaml中存在循环依赖导致iLogtail core dump的问题（issue #1503）
解决方案：yaml转json前进行循环依赖校验
> Prevent circular dependency crash in YAML parsing (to #1503)

- core/common/TimeUtil.cpp
- core/common/TimeUtil.h
- core/models/LogEvent.cpp
- core/models/MetricEvent.cpp
- core/models/PipelineEvent.h
- core/models/SpanEvent.cpp
- core/processor/daemon/LogProcess.cpp
- core/spl/PipelineEventGroupInput.cpp
- core/unittest/models/MetricEventUnittest.cpp
- core/unittest/models/SpanEventUnittest.cpp
- core/unittest/processor/ProcessorMergeMultilineLogNativeUnittest.cpp
- core/unittest/processor/ProcessorParseApsaraNativeUnittest.cpp
- core/unittest/processor/ProcessorParseDelimiterNativeUnittest.cpp
- core/unittest/processor/ProcessorParseRegexNativeUnittest.cpp
- 问题：启用EnableTimestampNanosecond但使用系统时间时，logGroup的time_ns仍然会被赋值0，前端展示会多9个0，后端认为开启纳秒功能进而降低查询性能。
注：本PR只解决C++部分的问题，Golang部分待 @Abingcbc 确认。
> fix: disable nanosecond timestamp when only EnableTimestampNanosecond is enabled

- core/config/Config.h
- core/file_server/FileDiscoveryOptions.cpp
- core/file_server/MultilineOptions.cpp
- core/input/InputContainerStdio.cpp
- core/input/InputContainerStdio.h
- core/input/InputFile.cpp
- core/input/InputFile.h
- core/input/InputObserverNetwork.cpp
- core/input/InputObserverNetwork.h
- core/pipeline/Pipeline.cpp
- core/pipeline/Pipeline.h
- core/pipeline/PipelineContext.h
- core/plugin/PluginRegistry.h
- core/plugin/instance/InputInstance.cpp
- core/plugin/instance/InputInstance.h
- core/plugin/instance/ProcessorInstance.h
- core/plugin/interface/Input.h
- core/processor/daemon/LogProcess.cpp
- core/unittest/config/ConfigUnittest.cpp
- core/unittest/input/InputContainerStdioUnittest.cpp
- core/unittest/input/InputFileUnittest.cpp
- core/unittest/pipeline/PipelineUnittest.cpp
- core/unittest/plugin/InputInstanceUnittest.cpp
- core/unittest/plugin/PluginMock.h
- core/unittest/plugin/ProcessorInstanceUnittest.cpp
- 背景：现有的内置处理插件（如多行切分，tag处理等）是pipeline级别的，对于一个pipeline存在多个input的情况不适用，因此需要调整为input级别。
- 方案：在Input类里增加mInnerProcessors成员，该成员在input插件Init时进行赋值。在处理时，处理线程首先会使用input里的内置处理插件，然后再使用pipeline级别的处理插件。
> make inner processors input-dependent resources instead of pipeline-dependent ones

- core/config/Config.cpp
- core/go_pipeline/LogtailPlugin.cpp
- core/pipeline/Pipeline.cpp
由于现有的C++ input插件都不支持一个pipeline配多个input，因此现有代码简单处理为所有C++输入插件都不允许多个，这在引入新C++输入插件后不再成立，需要进行调整，包括以下几点：
1. C++输入插件仅file、stdio、老observer、stream只能1个pipeline1个，其余C++输入插件不做此限制
2. 由于CGO接口目前支持log传递，不支持metric和span，因此对于采集metric和span的C++输入插件，不允许其使用Go的任何插件（包括处理和输出）
3. 当Go输出插件和C++输出插件共存时，C++输出插件允许且仅允许存在1个flusher_sls。
> relax pipeline topology restriction

- config_server/protocol/v2/README.md
- config_server/protocol/v2/agent.proto
1. capability bits开源留16个bit，从2^16开始留给第三方做二次扩展
2. request和response中都额外增加一个bytes opaque字段，留给第三方做二次扩展
3. 抽取相同的error_response部分
> refine config server v2 protocol

- .devcontainer/Dockerfile
- core/application/Application.cpp
- docs/cn/developer-guide/test/unit-test.md
- tools/coverage-diff/main.py
1. 将C++单测覆盖率统计工具加入到开发镜像中
2. 补充本地计算覆盖率的文档
3. 修复一些文件名过长，导致覆盖率报告跨两行出现的报错
4. 目前80%覆盖率要求过高，删除卡点，暂时由reviewer保证覆盖率质量
> add coverage tools to devcontainer

- core/common/MachineInfoUtil.cpp
- 问题：在启动发送本地磁盘文件时（上次退出时落盘的），当本地磁盘文件较大时，有一定概率导致core，堆栈信息如下：
排查下来大概率是由于定时检查ip变没变时调用的非可重入版本gethostbyname，与同步发送时curl使用的gethostbyname函数发生了data race。
- 解决方案：将gethostbyname改成线程安全且跨平台的getaddrinfo。
> fix core caused by concurrent use of non-thread-safe gethostbyname

- .devcontainer/Dockerfile
- core/unittest/event_handler/ModifyHandlerUnittest.cpp
修复两个小问题
1. 之前是间接引用了Pipeline.h，但是直接include的文件发生了变化，导致单测编译失败。
2. devcontainer里的user之前误删除了
> fix unittest include and devcontainer user

- core/checkpoint/CheckPointManager.cpp
- core/checkpoint/CheckPointManager.h
- core/event_handler/EventHandler.cpp
- core/reader/LogFileReader.cpp
- core/reader/LogFileReader.h
https://github.com/alibaba/ilogtail/pull/1620 只在内存的checkpoint中新增了一个字段，但是没有dump到本地文件中
1. checkpoint dump到本地文件的时候也要加一下idx in reader array字段
2. 其他一些命名不一致的优化
> fix checkpoint dump idx in reader array

- plugins/input/kafka/input_kafka.go
问题：kafka consumer 在关闭后仍然正常运行
由于 cancel 在 wait 之后调用，所以会导致一直 wait 而无法正常关闭，调整一下调用顺序
> fix: input_kafka consumer wont close due to ctx never done.

- core/application/Application.cpp
- core/event_handler/LogInput.cpp
- core/event_handler/LogInput.h
- core/input/InputFile.cpp
- core/input/InputFile.h
- core/monitor/LogtailMetric.cpp
- core/monitor/LogtailMetric.h
- core/monitor/LoongCollectorMetricTypes.h
- core/monitor/MetricConstants.cpp
- core/monitor/MetricConstants.h
- core/monitor/Monitor.cpp
- core/monitor/Monitor.h
- core/monitor/PluginMetricManager.h
- core/polling/PollingDirFile.cpp
- core/polling/PollingDirFile.h
- core/polling/PollingModify.cpp
- core/polling/PollingModify.h
- core/processor/ProcessorSPL.cpp
- core/processor/ProcessorSPL.h
- core/processor/daemon/LogProcess.cpp
- core/processor/daemon/LogProcess.h
- core/reader/LogFileReader.cpp
- core/reader/LogFileReader.h
- core/sender/Sender.cpp
- core/sender/Sender.h
- core/unittest/monitor/PluginMetricManagerUnittest.cpp
- pkg/protocol/decoder/opentelemetry/otlp_metric_parser.go
* 新增了LoongCollectorMonitor
* 改动代码在core/monitor/Monitor.h，core/monitor/Monitor.cpp
* 将原有的Gauge类型指标拓展为IntGauge和DoubleGauge
* 把指标类型移到了单独的文件core/monitor/LoongCollectorMetricTypes.h
* 大部分代码是Gauge改名为IntGauge
> feat: add loong collector monitor

- .devcontainer/Dockerfile
- config_server/service/Dockerfile
- core/dependencies.cmake
- docker/Dockerfile.ilogtail-build-linux
- docker/Dockerfile.ilogtail-toolchain-linux
- docker/Dockerfile_build
- docker/Dockerfile_coverage
- docker/Dockerfile_development_part
- docker/Dockerfile_goc
- docker/build-multi-arch-build-image.sh
1. 更新镜像依赖：
1. 编译两个fPIC的静态链接库，替代动态链接库
2. 将 libgmock.a 复制到 lib 目录下
2. 删除开发镜像中的 git
3. 修复 dockerfile 中由于 centos 源失效导致的问题
正确的方案还是尽快升级镜像版本，但是Centos7与8之间对于包管理方式，存在较大的差异，需要投入一定的时间。
> upgrade development image

- core/monitor/Monitor.cpp
- core/monitor/Monitor.h
每5秒检查一次cpu和内存是否达到硬限制（10倍设定上限），如果达到立即自杀
> suicide immediately when resource hard limit is met

- plugins/processor/gotime/processor_gotime.go
- plugins/processor/gotime/processor_gotime_test.go
作用：支持将日志里的纳秒时间转换成其他时间格式
日志样例：time:1645595256807000123
插件配置样例：
```yaml
enable: true
global:
EnableTimestampNanosecond: true
inputs:
- Type: input_file
FilePaths: 
- /workspaces/ilogtail_version2/bin/ilogtail/test.log
processors:
- Type: processor_regex
FullMatch: false
KeepSource: true
KeepSourceIfParseError: true
Keys:
- time
NoKeyError: true
NoMatchError: true
Regex: time:(.*)
SourceKey: content
- Type: processor_gotime
AlarmIfFail: true
DestFormat: '2006-01-02 15:04:05.000000000'
DestKey: timeNano
DestLocation: 8
KeepSource: true
NoKeyError: true
SetTime: true
SourceFormat: nanoseconds
SourceKey: time
SourceLocation: 8
flushers:
- Type: flusher_stdout
OnlyStdout: true
```
日志输出结果
```json
{"content":"time:1645595256807000123","time":"1645595256807000123","timeNano":"2022-02-23 …
```
> Add processor_gotime with nanosecond to other time format conversion capability

- plugins/processor/gotime/processor_gotime.go
- plugins/processor/gotime/processor_gotime_test.go
作用：支持将日志里的纳秒时间转换成其他时间格式
日志样例：time:1645595256807000123
插件配置样例：
```yaml
enable: true
global:
EnableTimestampNanosecond: true
inputs:
- Type: input_file
FilePaths: 
- /workspaces/ilogtail_version2/bin/ilogtail/test.log
processors:
- Type: processor_regex
FullMatch: false
KeepSource: true
KeepSourceIfParseError: true
Keys:
- time
NoKeyError: true
NoMatchError: true
Regex: time:(.*)
SourceKey: content
- Type: processor_gotime
AlarmIfFail: true
DestFormat: '2006-01-02 15:04:05.000000000'
DestKey: timeNano
DestLocation: 8
KeepSource: true
NoKeyError: true
SetTime: true
SourceFormat: nanoseconds
SourceKey: time
SourceLocation: 8
flushers:
- Type: flusher_stdout
OnlyStdout: true
```
日志输出结果
```json
{"content":"time:1645595256807000123","time":"1645595256807000123","timeNano":"2022-02-23 …
```
> [backport 1.8] Add processor_gotime with nanosecond to other time format conversion capability

- core/prometheus/schedulers/ScrapeScheduler.cpp
> fix the error in setting timestamp for Prometheus scrape metrics, which caused timestamp parameter overflow

- core/application/Application.cpp
- core/flusher/sls/FlusherSLS.cpp
- core/flusher/sls/FlusherSLS.h
- core/go_pipeline/LogtailPlugin.cpp
- core/plugin/interface/Flusher.cpp
- core/plugin/interface/Flusher.h
- core/queue/SenderQueueManager.cpp
- core/queue/SenderQueueManager.h
- core/unittest/flusher/FlusherSLSUnittest.cpp
- core/unittest/queue/SenderQueueManagerUnittest.cpp
- pluginmanager/logstore_config.go
- 问题：Go的profile信息无法发送到C++部分
- 原因：自监控没有独立的流水线，只有一个假的flusherSLS，而且这个flusher无法走常规的初始化流程，包括建队列等，因此go的自监控信息发送到C++会找不到相应的队列。
- 处理：特殊处理，发的时候看一下队列有没有，没的话现场建一个
> fix go profile send failure

- core/reader/FileReaderOptions.cpp
- test/e2e/test_cases/input_container_stdio_multiline/case.feature
应用侧写入日志可能存在延迟，例如，某一行日志写入一半之后，5秒内都没有写入后半行。从而触发超时强制读取，导致截断。
已知触发原因：
1. 日志框架缓存
2. 操作系统缓存
3. 磁盘IO
适当延长默认的超时时间
1. 多行依赖超时时间判断一组多行是否结束
2. C++ stdout依赖超时时间刷取最后一行
> fix: extend default timeout duration for reader flush

- core/pipeline/Pipeline.cpp
ebpf 不加任何 filter 时，event group大小为1024，目前塞不到 processqueue 里面去，就无法发到sls
如果改成1024，一个 event group 内存占用是3M～4M
> modify event group size

- docs/cn/configuration/system-config.md
- pkg/helper/container_discover_controller.go
`USE_CONTAINERD`这个环境变量真实作用是在有docker的情况下，仍然去探测containerd。探测不到，还会去用docker。
现在已经实现了所有运行时平等的探测，所以不再需要改环境变量。
为了兼容旧版本的行为，直接删除该变量。
> remove use_containerd to keep compatibility

- core/go_pipeline/LogtailPlugin.cpp
当前main分支编译出的ilogtail，当满足：
1. 运行时间较长
2. 配置中存在go pipeline
的条件时，如果变更配置，会导致流水线卡死
根本原因：go向c++ flusher发送自监控数据会失败，发送队列不可用。
为什么会导致卡死：当运行了足够长时间，自监控go pipeline的数据因为一直发不出去，堵塞到aggregator时，进行配置变更，会卡死在自监控go pipeline的aggregator stop处。这里有一个循环会一直等待数据能发送出去，但由于下游flusher发送不成功，导致整个循环退不出、进而导致死循环卡住。
之前的PR https://github.com/alibaba/ilogtail/pull/1709 已经尝试修复了这个问题，但是有一个地方的返回值错了，导致修复没有成功
> Fixed an issue where the pipeline would get stuck during configuration changes.

- plugins/input/canal/input_canal.go
Fixed an issue where the input_canal plugin used GTID as the sync method even when gtid_enabled was set to false. This led to syncing from the beginning due to receiving an empty GTID set. Syncing from the beginning is usually undesirable as it consumes significant CPU resources on the server side and deviates from the default plugin behavior. This commit ensures that the plugin respects the gtid_enabled switch and the gtid_mode query result.
> fix: do not use gtid if gtid is disabled

- .github/workflows/build-core-ut.yaml
- docker/Dockerfile_coverage
- tools/coverage-diff/main.py
现在统计增量覆盖率，比较粗放。直接统计每个修改文件的单测覆盖率。这就导致修改老文件时，覆盖率一直失败。
目前，没有已有的工具能够计算本次提交中代码的覆盖率。所以，写了一个python脚本，大概原理如下：
1. git diff获取文件中+的代码行号
2. gcovr 计算所有代码的覆盖情况，输出成json
3. diff代码与gcovr结果求交集，得到有效代码，统计这些有效代码中的覆盖和没覆盖的条数
4. 计算覆盖率
> test: calculate incremental unittest coverage

- core/prometheus/schedulers/ScrapeConfig.cpp
- core/unittest/prometheus/ScrapeConfigUnittest.cpp
enable-compression 依赖 libcurl 中的 Accpet-Encoding option，短时间先关掉这个配置
> update: remove enable-compression config temporarily

- plugins/input/kafka/input_kafka.go
> Add a default content key for the service_kafka plugin

- core/monitor/metric_constants/MetricConstants.h
- core/monitor/metric_constants/PluginMetrics.cpp
- core/monitor/metric_constants/RunnerMetrics.cpp
- core/plugin/input/InputPrometheus.cpp
- core/prometheus/Constants.h
- core/prometheus/PromSelfMonitor.cpp
- core/prometheus/PromSelfMonitor.h
- core/prometheus/PrometheusInputRunner.cpp
- core/prometheus/PrometheusInputRunner.h
- core/prometheus/schedulers/ScrapeScheduler.cpp
- core/prometheus/schedulers/ScrapeScheduler.h
- core/prometheus/schedulers/TargetSubscriberScheduler.cpp
- core/prometheus/schedulers/TargetSubscriberScheduler.h
- core/unittest/input/InputPrometheusUnittest.cpp
- core/unittest/prometheus/CMakeLists.txt
- core/unittest/prometheus/PromSelfMonitorUnittest.cpp
- core/unittest/prometheus/PrometheusInputRunnerUnittest.cpp
- core/unittest/prometheus/ScrapeSchedulerUnittest.cpp
- core/unittest/prometheus/TargetSubscriberSchedulerUnittest.cpp
指标 | 描述 | labels | 类型
-- | -- | -- | --
prom_register_state | 注册状态 | pod_name,operator_host,operator_port | IntGauge
prom_register_retry_total | 注册重试 | status,pod_name,... | Counter
prom_job_num | 输入插件（Job）数量 | pod_name,... | IntGauge
prom_subsricbe_targets | 订阅的 Targets 数量 | job,pod_name,... | IntGauge
prom_subsricbe_total | 订阅次数总量 | status,job,pod_name,... | Counter
prom_subsricbe_time_ms | 订阅耗时（分布） | status,job,pod_name,... | IntGauge
prom_scrape_total | 采集次数总量 | status,target,job,pod_name,... | Counter
prom_scrape_bytes_total | 采集总字节数 | status,target,job,pod_name,... | Counter
prom_scrape_time_ms | 采集耗时（分布） | status,target,job,pod_name,... | IntGauge
prom_scrape_delay_total | 采集延迟总量  | status,target,job,pod_name,... | Counter
> feat: prometheus self monitor metrics

- core/reader/LogFileReader.cpp
This pull request introduces a small but important change to the `LogFileReader` class in the `core/reader/LogFileReader.cpp` file. The modification adjusts the size of the `containerBOMBuffer` array to ensure correct container type checking and prevent memory overruns.
* [`core/reader/LogFileReader.cpp`](diffhunk://#diff-c4ac3e4e54f269c40ee3c6cfdc4f41148b532ad0aa1b19949c994553c283d6b1L690-R690): Increased the size of the `containerBOMBuffer` array from 1 to 2 in the `checkContainerType` method.
> Fix the checkContainerType out-of-bounds memory issue

- core/runner/ProcessorRunner.cpp
SPL 采用一种类似回调的方式填充 group。如果没有返回数据，那么不会向返回列表中填充 group。
并且此时，属于解析正常，不会报error。
因此，导致后续 ProcessorRunner 中出现数组越界 core。
https://github.com/alibaba/ilogtail/blob/a13bc6f096da042d780be7c91dc798490e0087ff/core/runner/ProcessorRunner.cpp#L194-L196
- main分支
- LoongCollector 0.1 版本
出现越界的地方属于旧版可观测代码，可以删除。
> fix: remove deprecated profile in ProcessorRunner

- core/file_server/event/BlockEventManager.cpp
- core/file_server/event/BlockEventManager.h
- core/file_server/event_handler/LogInput.cpp
- core/unittest/event/BlockedEventManagerUnittest.cpp
- core/unittest/event/CMakeLists.txt
- core/unittest/reader/ForceReadUnittest.cpp
- 问题：在压测的时候小概率出现LogInput和Processor线程同时死锁
- 原因：两个线程获取两把锁的顺序相反
- 处理线程：先获取处理队列的锁（ProcessQueueManager::mQueueMux），然后pop数据。如果队列变成低水位了，会调用BlockedEventManager::Feedback函数，该函数会对BlockEventMap加锁（BlockedEventManager::mLock）；
- input线程：在定时调用GetTimeoutEvent函数时，首先对BlockEventMap加锁，然后通过ProcessQueueManager::IsValidToPush函数判断event对应的队列是否可用，这个时候会对处理队列加锁。
- 影响范围：仅main分支，2.0旧版实现在启用优先级队列后也有概率触发
- 解决方案：Feedback函数里仅保存信息，在LogInput线程里去消费这些feedback。
> fix deadlock on LogInput and Processor Runner thread

- core/common/common.cmake
- core/common/http/AsynCurlRunner.cpp
- core/common/http/Curl.cpp
- core/common/http/HttpRequest.cpp
- core/common/http/HttpRequest.h
- core/common/http/HttpResponse.cpp
- core/common/http/HttpResponse.h
- core/metadata/K8sMetadata.cpp
- core/plugin/flusher/sls/SLSResponse.cpp
- core/prometheus/async/PromFuture.cpp
- core/prometheus/async/PromHttpRequest.cpp
- core/prometheus/async/PromHttpRequest.h
- core/prometheus/schedulers/BaseScheduler.h
- core/prometheus/schedulers/ScrapeScheduler.cpp
- core/prometheus/schedulers/ScrapeScheduler.h
- core/prometheus/schedulers/TargetSubscriberScheduler.cpp
- core/prometheus/schedulers/TargetSubscriberScheduler.h
- core/runner/sink/http/HttpSink.cpp
- core/runner/sink/http/HttpSinkRequest.h
- core/unittest/common/http/CurlUnittest.cpp
- core/unittest/common/timer/HttpRequestTimerEventUnittest.cpp
- core/unittest/prometheus/PromAsynUnittest.cpp
- core/unittest/prometheus/ScrapeSchedulerUnittest.cpp
- core/unittest/prometheus/TargetSubscriberSchedulerUnittest.cpp
- 背景：在Prometheus抓取场景，对于大流量的target（一次抓取有30MB），从http请求到生成event group会经历多次字符串拷贝：
1. http response body是分批写入目标字符串的，因此会不可避免的经历多次内存重新分配。使用stringstream能够避免写入时的再分配，但是最终转成string时仍需要进行一次完整的分配；
2. 对于获取的body，在完成按行切分生成Log event时，仍然需要将对应的内容拷贝到event group的source buffer里；
内存profile结果表明，这两步占了近40%的内存开销，因此需要优化。
- 方案：
1. 放开response body的stirng类型限制，改成void*，即任意类型，同时支持自定义的body data回调函数。
2. 对于Prometheus抓取场景，可自定义body类型PromHttpResponse，其中记录event group和string cache。同时在自定义的body data回调函数中（PromDataWriteCallback）对数据流进行实时按行切分并生成Log Event。通过这种方式，能够基本避免前面所说的多次无效内存拷贝，提升整体效率。
> support custom http response body and body data write callback

- pkg/helper/k8smeta/k8s_meta_cache.go
- pkg/helper/k8smeta/k8s_meta_const.go
- pkg/helper/k8smeta/k8s_meta_link.go
- plugins/input/kubernetesmetav1/input_kubernetes_meta.go
- plugins/input/kubernetesmetav1/kubernetes_collect.go
- plugins/input/kubernetesmetav1/kubernetes_collect_core.go
- plugins/input/kubernetesmetav2/meta_collector.go
- plugins/input/kubernetesmetav2/meta_collector_core.go
- plugins/input/kubernetesmetav2/service_meta.go
> fix: remove list watch secret in K8s Meta

- test/engine/steps.go
- test/engine/trigger/protocol.go
Supports triggering HTTP requests and counting specific log entries.
> HTTP Trigger && Count Logs

- core/monitor/LogtailAlarm.cpp
1. 统一自监控模块SenderQueue的Key的格式为project-logstore
2. 修复SenderQueueKey不存在导致的alarm发送失败问题
> Fix alarm send fail

- core/file_server/reader/LogFileReader.cpp
- core/file_server/reader/LogFileReader.h
- core/runner/ProcessorRunner.cpp
- 问题：windows下的logPath需要转码才能显示正常
- 影响：1.8改造的时候就把这个给漏了。因为此问题只有windows才有，而windows从1.6之后没有发过版，因此没有线上影响。
> fix: convert chinese log path on windows

- config_server/protocol/v2/README.md
- config_server/protocol/v2/agentV2.proto
Change-Id: I58a7d73be66857967f6c0f54cd67877ee6945dae
给管控协议的流水线下发及操作指令增加一个额外可选的上下文，用来传递一些额外信息。
> feat: add context for config server v2 pb

- core/file_server/event/BlockEventManager.cpp
- core/file_server/event_handler/LogInput.cpp
- core/file_server/event_handler/LogInput.h
- 现状：当LogInput线程没有事件的时候，会等待20ms再尝试读取事件。如果在这等待时间里，处理队列空了，理论上应该立刻读取相应的block event，但是实际只能等到睡眠结束才能读。对于大流量的日志场景，会严重影响读取性能（约有30%的性能损耗）
- 方案：增加一个通信机制，处理队列空了以后立刻读取block event。
> read blocked event as soon as process queue triggers feedback to improve file reading performance

- pkg/helper/docker_center.go
问题描述： docker compose环境下，会发现容器信息发现模块会获取的created状态的容器，参见https://alidocs.dingtalk.com/i/nodes/N7dx2rn0JbxOaqnACxvaegn5WMGjLRb3
复现条件：
docker compose up -d命令，启动一个容器之后，修改docker-compose.yaml文件，然后再执行docker compose up -d
问题原因分析：
从事件顺序可以看到，新旧容器的交替顺序是这样的：
新容器create(其他名字)，旧容器杀、停、删，新容器rename，新容器start
事件监听rename的时候，会fetchone，rename的时候，容器还没有start，此时fetchone获取的就是created状态的容器信息。标准输出的插件里面，会根据containerID缓存容器信息，所以及时后面fetchone又更新了容器信息，标准输出也感知不到
修复方案：
fetchone里强校验容器状态
> Fix the issue of missing container information caused by the event sequence when docker compose is repeatedly up.

- config_server/protocol/v2/README.md
- config_server/protocol/v2/agentV2.proto
- core/config/common_provider/CommonConfigProvider.cpp
> feat: add configer provider info report interface

- core/app_config/AppConfig.cpp
- core/app_config/AppConfig.h
- core/common/version.h
This pull request introduces several new utility methods and constants to the `AppConfig` class in the `core/app_config` module. These changes aim to enhance the configuration management and file naming conventions based on the `logtail_mode` flag.
Key changes include:
* Added `GetSymLinkName` method to determine the symbolic link name based on the `logtail_mode` flag.
* Added `GetPidFileName` method to generate the PID file name depending on the `logtail_mode` flag.
* Added `GetAgentPrefix` method to return the appropriate prefix for the agent based on the `logtail_mode` flag.
* Declared the new utility methods (`GetSymLinkName`, `GetPidFileName`, and `GetAgentPrefix`) in `core/app_config/AppConfig.h`.
* Introduced `LOONGCOLLECTOR_PREFIX` constant in `core/common/version.h` to support …
> SymLinkName, PidFileName, and AgentPrefix support logtail_mode.

- core/pipeline/Pipeline.cpp
- core/pipeline/batch/Batcher.h
- core/pipeline/plugin/instance/FlusherInstance.cpp
- core/pipeline/plugin/instance/FlusherInstance.h
- core/pipeline/plugin/interface/Flusher.h
- core/unittest/pipeline/PipelineUnittest.cpp
- core/unittest/plugin/FlusherInstanceUnittest.cpp
问题在于Batcher预留了Index用于区分不同的flusher但是之前没有实现，全都是默认的0，导致部分数据拿不出来并延迟发送。
当初开发Batcher的时候并没有多flusher的说法
> Fix: fix flushing delay when multiple flushers exist

- docs/cn/plugins/input/service-otlp.md
- pkg/protocol/decoder/opentelemetry/otlpDataToSLSProto.go
- plugins/input/opentelemetry/service_otlp_v1_test.go
This pull request includes changes to the `service_otlp` plugin documentation and the `ConvertOtlpTraceV1` function to improve functionality and accuracy. The most important changes are detailed below:
Documentation updates:
* [`docs/cn/plugins/input/service-otlp.md`](diffhunk://#diff-f848e2e156c29dd9454c0be16604ae284a69c302916bda7538ade53789190865L5-R5): Removed the note about not supporting OTLP trace conversion to SLSProto, indicating that this functionality is now supported.
Functionality improvements:
* [`pkg/protocol/decoder/opentelemetry/otlpDataToSLSProto.go`](diffhunk://#diff-bca3635bdf846ceebfdf96393ff2c3a38d4e2b03442841f2b3a2ec33ed4568e4L430-R431): Updated the `ConvertOtlpTraceV1` function to convert OTLP traces to logs using the `ConvertTrace` function, removing the previous …
> Enable OTLP Trace flushing to SLS

- core/runner/ProcessorRunner.cpp
当group push失败时，group就已经被move走了，再次调用push会导致空的group。
ps：理论上这段逻辑不应该走到，具体原因还要再看下
> fix core caused by failed queue push

- pkg/helper/docker_center.go
> fix: Handle timeout for exited containers in docker discover process

- core/prometheus/PrometheusInputRunner.cpp
- core/prometheus/schedulers/BaseScheduler.cpp
- core/prometheus/schedulers/BaseScheduler.h
- core/prometheus/schedulers/ScrapeScheduler.cpp
- core/prometheus/schedulers/TargetSubscriberScheduler.cpp
- core/unittest/prometheus/ScrapeSchedulerUnittest.cpp
将原来的 Curl 执行时间作为采集时间戳不准确，因为：从指定的调度执行时间到 Curl 执行时间的间隔不可控，会出现某个 Targets 的实际采集间隔小于指定间隔如（14.932s < 15s）
> fix: add mLatestScrapeTime for scrapeTimestamp

- docs/cn/installation/start-with-k8s.md
- example_config/start_with_k8s/loongcollector-daemonset.yaml
- example_config/start_with_k8s/loongcollector-ns.yaml
- example_config/start_with_k8s/loongcollector-secret.yaml
- example_config/start_with_k8s/loongcollector-user-configmap.yaml
- scripts/dist.sh
This pull request includes a change to the `scripts/dist.sh` file to improve the organization of configuration files in the distribution package.
Changes to configuration file organization:
* [`scripts/dist.sh`](diffhunk://#diff-6990843536db1b99b0db9f59903b8eca02fb24964007bde1e3420b3688e5bde3R44-R46): Added a new directory for continuous pipeline configuration and adjusted the copy command to place the configuration files in the newly created directory.
> Added a new directory for continuous pipeline configuration when make dist

- pkg/go.mod
- pkg/helper/docker_center.go
- pkg/helper/docker_center_test.go
- pkg/helper/docker_cri_adapter.go
- plugins/input/docker/stdout/input_docker_stdout.go
…nter and add UT to this module (#1938)
* refine docker center code
* fix comments
* fix comments Conflicts:
pkg/helper/docker_center.go
> [backport]: Fix the problem of increasing container meta information in Docker Center and add UT to this module (#1938)

- core/ebpf/SourceManager.cpp
- core/ebpf/SourceManager.h
- core/ebpf/config.cpp
- core/ebpf/eBPFServer.cpp
- core/ebpf/include/export.h
- core/plugin/flusher/sls/FlusherSLS.cpp
1. Synchronize export.h:
Updated export.h to ensure consistency across the codebase. All necessary declarations and definitions are now properly synchronized.
2. Leverage destructor for stop functionality:
Implemented the stopAll functionality within the destructor to ensure a clean and automatic resource cleanup when objects go out of scope, enhancing robustness and reducing the likelihood of resource leaks.
3. Fix memory violation in FlusherSLS:
In FlusherSLS, the DealSenderQueueItemAfterSend function was releasing the pipeline object prematurely, which could lead to memory violations if the pipeline member was accessed afterward.
> synchronize eBPF lib header

- core/runner/ProcessorRunner.cpp
- core/runner/sink/http/HttpSink.cpp
Flusher在OnSendDone中会将item从队列中移出，后续由于Pipeline被释放，所以导致访问空指针。
修复：在处理之前，先持有Pipeline对象，避免其被释放。
配置变更时，ProcessRunner在处理完旧Pipeline残留在处理队列的数据时，再将其塞入到发送队列或者Go流水线。
1. 发送队列：由于发送队列复用，数据会走新流水线。
2. Go流水线：Go流水线可能已被停止。数据会发送失败。
修复：在处理完之后，统一走新流水线发送数据。
后续在配置变更测试中，统一补充测试用例。
> fix: use released pipeline pointer

- core/file_server/event_handler/LogInput.h
- core/monitor/Monitor.h
- core/pipeline/PipelineManager.cpp
- core/pipeline/PipelineManager.h
- core/unittest/config/CommonConfigProviderUnittest.cpp
- core/unittest/config/ConfigUpdateUnittest.cpp
- core/unittest/config/PipelineManagerMock.h
- core/unittest/pipeline/CMakeLists.txt
- core/unittest/pipeline/PipelineUpdateUnittest.cpp
在多个配置加载时，需要根据input_file判断isFileServerInputChanged，从而决定是否启动FileServer。但是之前PR修改，导致后一个配置的结果可以覆盖前一个配置。
任意一个配置改变了input_file，isFileServerInputChanged都应该是true
> fix: judge file server changed

- core/app_config/AppConfig.cpp
- core/app_config/AppConfig.h
This pull request includes changes to the `core/app_config/AppConfig.cpp` file. The changes introduce conditional compilation for the `logtail_mode` flag and modify the `GetSymLinkName` function to simplify its logic.
Changes to conditional compilation:
* [`core/app_config/AppConfig.cpp`](diffhunk://#diff-7c2e04058fb2ce8c0c2fa83dfabc4bdc6335414d223a61389352b10ffdff02edR47-R51): Added preprocessor directives to set the `logtail_mode` flag to true for enterprise builds and false otherwise.
Simplification of function logic:
* [`core/app_config/AppConfig.cpp`](diffhunk://#diff-7c2e04058fb2ce8c0c2fa83dfabc4bdc6335414d223a61389352b10ffdff02edL524-L529): Modified the `GetSymLinkName` function to remove the conditional check for `logtail_mode`, simplifying the function's logic.
> set the `logtail_mode` flag to true for enterprise builds

- plugins/flusher/opentelemetry/flusher_otlp.go
- plugins/flusher/opentelemetry/flusher_otlp_test.go
Change-Id: I8948322d1e54a61c7b17968a5bcaf5590d9a437c
> fix: flusher_otlp stop nil log/metric/trace client

- core/reader/LogFileReader.cpp
- core/reader/LogFileReader.h
- core/unittest/reader/GetLastLineDataUnittest.cpp
- core/unittest/reader/RemoveLastIncompleteLogUnittest.cpp
- **修复了因特定日志条目导致的崩溃问题**  
例如：\n2021-08-25T07:00:00.000000000Z stdout F xxx 导致的日志崩溃。
- **优化了在行尾多行模式匹配到 "xxx\nend" 时的日志回退逻辑**  
这种情况下应该因为end没有换行符，应该回退所有日志
- **解决了行尾多行模式下当 containerd 日志以 "xxx\nend\npart log" 格式出现时的日志回退问题**  
例如，在遇到以下日志序列时，如果 "end log" 匹配成功，则应将日志回退至 "2021-08-25T07:00:00.000000000Z stdout F end log" 的位置，回退行数为3行：
```
2021-08-25T07:00:00.000000000Z stdout F unmatch log
2021-08-25T07:00:00.000000000Z stdout F unmatch log
2021-08-25T07:00:00.000000000Z stdout F unmatch log
2021-08-25T07:00:00.000000000Z stdout F end log
2021-08-25T07:00:00.000000000Z stdout P unmatch log
2021-08-25T07:00:00.000000000Z stdout P unmatch log
2021-08-25T07:00:00.000000000Z stdout P unmatch log
```
> [backport]: fix GetLastLine core

- core/file_server/reader/LogFileReader.cpp
- core/file_server/reader/LogFileReader.h
- core/unittest/reader/GetLastLineDataUnittest.cpp
- core/unittest/reader/RemoveLastIncompleteLogUnittest.cpp
- **修复了因特定日志条目导致的崩溃问题**  
例如：\n2021-08-25T07:00:00.000000000Z stdout F xxx 导致的日志崩溃。
- **优化了在行尾多行模式匹配到 "xxx\nend" 时的日志回退逻辑**  
这种情况下应该因为end没有换行符，应该回退所有日志
- **解决了行尾多行模式下当 containerd 日志以 "xxx\nend\npart log" 格式出现时的日志回退问题**  
例如，在遇到以下日志序列时，如果 "end log" 匹配成功，则应将日志回退至 "2021-08-25T07:00:00.000000000Z stdout F end log" 的位置，回退行数为3行：
```
2021-08-25T07:00:00.000000000Z stdout F unmatch log
2021-08-25T07:00:00.000000000Z stdout F unmatch log
2021-08-25T07:00:00.000000000Z stdout F unmatch log
2021-08-25T07:00:00.000000000Z stdout F end log
2021-08-25T07:00:00.000000000Z stdout P unmatch log
2021-08-25T07:00:00.000000000Z stdout P unmatch log
2021-08-25T07:00:00.000000000Z stdout P unmatch log
```
> fix GetLastLine core

- core/unittest/pipeline/PipelineUpdateUnittest.cpp
- test/engine/setup/subscriber/sls.go
- tools/coverage-diff/main.py
1. 修复商业版 PipelineUpdateUnittest
2. 目前整体覆盖率已经到达60%，提高单测准入门槛到 60%
> fix: pipelineupdateunittest enterprise ut

- plugins/flusher/prometheus/flusher_prometheus_test.go
flusher_prometheus 的单测有一个 http mock server 去采集数据，将数据填充到 slice时有并发问题，可能会导致漏统计一些数据，加一个锁保护。
本地go test -count 100，未发现问题。
> fix ut: http mock server protects the result slice with lock

- pkg/helper/k8smeta/k8s_meta_cache.go
- pkg/helper/k8smeta/k8s_meta_deferred_deletion_meta_store.go
- pkg/helper/k8smeta/k8s_meta_deferred_deletion_meta_store_test.go
- pkg/helper/k8smeta/k8s_meta_http_server.go
- pkg/helper/k8smeta/k8s_meta_http_server_test.go
- pkg/helper/k8smeta/k8s_meta_link.go
- pkg/helper/k8smeta/k8s_meta_manager.go
- plugins/input/kubernetesmetav2/meta_collector.go
- plugins/input/kubernetesmetav2/meta_collector_batch.go
- plugins/input/kubernetesmetav2/meta_collector_core.go
- plugins/input/netping/netping_test.go
由于存在多个对象index相同的情况，所以索引中的value是一个数组。但是处理update事件时没有覆盖旧的索引，导致重复发送。
1. 将索引底层更换为一个set
2. 修复生成link的逻辑
3. 调整一些字段，Job的Status和namespace的label序列化为json
> fix: k8s meta index

- .devcontainer/Dockerfile
https://superuser.com/questions/869144/why-does-the-system-have-etc-sudoers-d-how-should-i-edit-it
sudoer.d 目前下的文件名不能包含 ~和.
如果 username name 有 `.`, 则无法被授予 root 权限。
> fix: docker file Root role, sudoer.d/ file name can not .

- pkg/helper/docker_center.go
- pkg/helper/docker_center_file_discover.go
- pkg/helper/docker_cri_adapter.go
- plugins/input/docker/logmeta/metric_container_info.go
- plugins/input/docker/logmeta/metric_container_info_test.go
- plugins/input/journal/unit.go
**问题描述:**
当用户在 Kubernetes 配置中使用以多个斜杠开头的挂载路径时(如 `//test/log`),会导致 formateContainerPath 获取到的挂载路径与采集配置中的 idf.LogPath 路径(`/test/log`)不匹配,从而引发数组越界问题。
例如以下挂载配置:
```yaml
volumeMounts:
- mountPath: //test/log/
name: volume-123123 
subPath: test
```
采集路径为`/test/log/**/*.log`
**修复方案:**
优化 formatPath 函数,确保当路径以斜杠开头时,只保留一个斜杠,使路径格式符合标准规范。
> handle multiple consecutive slashes in the path string.

- pkg/helper/docker_center.go
- pkg/helper/docker_center_file_discover.go
- pkg/helper/docker_cri_adapter.go
- plugins/input/docker/logmeta/metric_container_info.go
- plugins/input/docker/logmeta/metric_container_info_test.go
- plugins/input/journal/unit.go
**问题描述:**
当用户在 Kubernetes 配置中使用以多个斜杠开头的挂载路径时(如 `//test/log`),会导致 formateContainerPath 获取到的挂载路径与采集配置中的 idf.LogPath 路径(`/test/log`)不匹配,从而引发数组越界问题。
例如以下挂载配置:
```yaml
volumeMounts:
- mountPath: //test/log/
name: volume-123123 
subPath: test
```
采集路径为`/test/log/**/*.log`
**修复方案:**
优化 formatPath 函数,确保当路径以斜杠开头时,只保留一个斜杠,使路径格式符合标准规范。
> [backport]: handle multiple consecutive slashes in the `path` string.

- plugins/input/docker/logmeta/metric_container_info.go
This pull request introduces changes to the `InputDockerFile` struct and related methods in the `plugins/input/docker/logmeta/metric_container_info.go` file to support a new feature for forcefully releasing stopped container files based on an environment variable.
Key changes include:
* **Struct Modification:**
* Added a new boolean field `forceReleaseStopContainerFile` to the `InputDockerFile` struct to track the environment variable status.
* **Initialization:**
* Modified the `Init` method to set the `forceReleaseStopContainerFile` field based on the `FORCE_RELEASE_STOP_CONTAINER_FILE` environment variable.
* **Collect Method:**
* Updated the `Collect` method to conditionally delete metrics and mappings of stopped containers based on the `forceReleaseStopContainerFile` flag.
> [backport 2.0] allowing for the forced release of stopped container files based on an environment variable(FORCE_RELEASE_STOP_CONTAINER_FILE)

- core/monitor/Monitor.cpp
- core/monitor/Monitor.h
资源超限时候，LogtailMonitor有个死锁，会导致进程一分钟强制退出。
suicide发出stop信号后，主线程会逐一进行stop，但这个monitor的stop中又去尝试获取同一把锁
导致stop死锁，无法正常退出。
需要确保发出stop信号时，这个锁已经释放，才能正常执行stop操作。
> Fix LogtailMonitor's deadlock when suicide

- core/plugin/processor/inner/ProcessorTagNative.cpp
- core/unittest/processor/ProcessorTagNativeUnittest.cpp
开发Tag处理插件的时候，__source__是个特殊的tag，需要在处理插件临时设置一个tag，然后在序列化的时候填入到PB的source字段。处理插件中遗漏设置临时tag了。
> fix: C++ source tag

- core/app_config/AppConfig.cpp
- core/unittest/app_config/AppConfigUnittest.cpp
- pkg/flags/flags.go
回退 #2037 中不保留gflag同名小写字母环境变量自动转flag的行为
原因：
1. 提升开源友好性：
- 开源维护者可以直接使用原始flag名称作为环境变量
- 无需强制使用 LOON_upperflagname 格式，便于开源共建
2. 简化配置管理：
- 进程级配置参数和环境变量可以使用统一的命名规则
- 减少维护两套命名规范的心智负担
- 降低配置出错的可能性
变更内容：
- 移除了 AppConfig.cpp 中的环境变量白名单过滤
- 调整 flags.go 中的环境变量处理逻辑，支持直接使用flag名称作为环境变量
> revert: restore direct environment variable to flag mapping for better maintainability

- plugin_main/plugin_main_test.go
- pluginmanager/logstore_config.go
- pluginmanager/plugin_manager.go
**定位过程**
通过一段时间前后的内存profile可以发现，createLogstoreConfig函数内存一直在上涨。
**问题原因:**
在createLogstoreConfig函数中，会出现
`contextImp := &ContextImp{}
logstoreC := &LogstoreConfig{
Context: contextImp,
}
contextImp.logstoreC = logstoreC`
这样的循环引用，实际测试下来，这种循环引用会导致LogstoreConfig不会被gc回收，从而在配置变化频繁的情况下内存一直上涨
**修复方案:**
对LogstoreConfig进行删除的时候，显式的把依赖中的对象设置成nil，解除循环依赖，保证LogstoreConfig对象会被gc回收
修复前后内存趋势对比
> Fixed the issue in golang code where the logstoreconfig object would not be recycled by GC due to circular references.

- test/config/context.go
- test/engine/steps.go
- test/engine/trigger/log/file.go
- test/engine/trigger/log/remote_file.py
之前默认5秒轮转导致一些复杂的测试用例不够稳定，新增支持每个测试用例自定义日志轮转的时间间隔。
> test: support custom log rotate interval

- pluginmanager/config_update_test.go
- pluginmanager/logstore_config.go
- pluginmanager/plugin_manager.go
- plugins/flusher/checker/flusher_checker.go
在flusher不ready的情况下，go流水线会将数据先暂存在flusheroutStore。当配置重新加载时，需要将旧流水线发送不出去的数据迁移到新流水线继续发送。
> fix: merge old pipeline data to new pipeline when flusher is unready

- core/config/common_provider/CommonConfigProvider.cpp
- core/config/common_provider/CommonConfigProvider.h
- core/config/feedbacker/ConfigFeedbackReceiver.cpp
- core/config/provider/ConfigProvider.h
This pull request includes changes to the `ConfigFeedbackReceiver` class in the `core/config/feedbacker/ConfigFeedbackReceiver.cpp` file. The main goal of these changes is to improve thread safety by ensuring that the `Feedback*ConfigStatus` methods do not hold a lock while calling the `Feedback*ConfigStatus` methods on the `feedbackable` objects.
Thread safety improvements:
* [`core/config/feedbacker/ConfigFeedbackReceiver.cpp`](diffhunk://#diff-8e6ba8f0972071604471fb465367c2fedfb5ce7b16daebf70d630cace661bc93R64-R106): Modified the `FeedbackContinuousPipelineConfigStatus`, `FeedbackInstanceConfigStatus`, and `FeedbackOnetimePipelineConfigStatus` methods to first find and store the `feedbackable` object under a lock, and then call the corresponding `Feedback*ConfigStatus` method outside …
> prevents potential deadlocks and improves thread safety.

- core/application/Application.cpp
- core/collection_pipeline/CollectionPipelineManager.cpp
- core/collection_pipeline/CollectionPipelineManager.h
- core/plugin/processor/inner/ProcessorTagNative.cpp
1. 问题：具体原因见待办。
解决方案：进程退出时手动先释放pipeline。
2. 问题：配置加载时主线程会修改map，SendPb、ProcessRunner两个线程会读取map。正常情况下，不会出现读取和修改map中的同一元素。加锁是为了进一步保护。
解决方案：CollectionPipelineManager并发加锁。
3. 问题：tag值为空的时候不应该上传
解决方案：添加tag时判断一下。
> fix: release pipelines manually before process exit

- docs/cn/plugins/input/extended/service-kubernetesmeta-v2.md
- pkg/helper/k8smeta/k8s_meta_const.go
- pkg/helper/k8smeta/k8s_meta_http_server.go
- pkg/helper/k8smeta/k8s_meta_link.go
- pkg/helper/k8smeta/k8s_meta_link_test.go
- plugins/input/kubernetesmetav2/meta_collector.go
- plugins/input/kubernetesmetav2/meta_collector_app.go
- plugins/input/kubernetesmetav2/meta_collector_batch.go
- plugins/input/kubernetesmetav2/meta_collector_core.go
- plugins/input/kubernetesmetav2/meta_collector_networking.go
- plugins/input/kubernetesmetav2/service_meta.go
1. K8s Meta中的relation type是个没有标准答案的东西，为了避免之后再反复调整需要重新出版本，不在代码里hardcode，移到配置文件中，让用户自己指定。
2. 之前配置了relation两端的entity之后，自动就生成relation了。relation没法删除。
解决方案：支持K8s Meta中所有关系名可配置化，不配置就默认删除。
一个node上的多个Pod非常可能会复用node ip作为pod ip，导致通过Host IP查询到的K8s Meta数据不全。
解决方案：以Pod UID作为返回值的key。
> fix: improve k8s entity relation type name

- core/collection_pipeline/batch/TimeoutFlushManager.cpp
- core/collection_pipeline/batch/TimeoutFlushManager.h
- 问题：处理线程会定时调用FlushTimeouBatch，原有代码为了避免死锁，将遍历map和执行flush操作分开来了，但是导致了非原子性。如果遍历完map后，pipeline正好析够掉，那么flush的时候flusher指针就是非法的。
- 影响：配置更新时小概率会触发，版本为loongcollector
- 解决：普通锁改成可重入锁，保证FlushTimeouBatch的原子性
> fix use after free core in timeout flush manager during pipeline update

- core/prometheus/component/StreamScraper.cpp
- core/prometheus/component/StreamScraper.h
When the length of a single sample exceeds 8192 bytes, the scraper will drop the sample. Set this value via an environment variable to make it configurable.
> Chore: Add env to control max sample length

- core/collection_pipeline/CollectionPipeline.cpp
- core/collection_pipeline/batch/TimeoutFlushManager.cpp
- core/collection_pipeline/batch/TimeoutFlushManager.h
- core/unittest/batch/TimeoutFlushManagerUnittest.cpp
- core/unittest/pipeline/PipelineUnittest.cpp
- 原因：
- 处理线程：Batcher.Add (加锁1）-> TimeoutFlushManager.UpdateRecord （加可重入锁2）
- 0号处理线程：TimeoutFlushManager.FlushoutBatch（加可重入锁2）-> Batcher.FlushQueue（加锁1） -> TimeoutFlushManager.UpdateRecord （加可重入锁2）
- 主线程：Batcher.FlushAll（加锁1）->（释放锁1）-> TimeoutFlushManager.ClearRecords（加可重入锁2）
- 影响：LoongCollector 3.0.7 且开启多个处理线程
- 解决：打破TimeoutFlushManager.FlushoutBatch（加可重入锁2）-> Batcher.FlushQueue（加锁1）的锁嵌套，回到上次代码修改前的状态，重新解决之前的core问题，通过标记删除的方式来避免指针失效。
- 结果：
- 处理线程：Batcher.Add (加锁1）-> TimeoutFlushManager.UpdateRecord （加锁2）
- 0号处理线程：TimeoutFlushManager.FlushoutBatch（加锁2）->（释放锁2）-> （加锁3） -> Batcher.FlushQueue（加锁1） -> TimeoutFlushManager.UpdateRecord （加锁2）
- 主线程：Batcher.FlushAll（加锁1）->（释放锁1）-> TimeoutFlushManager.ClearRecords（加锁3）
> fix deadlock in TimeoutFlush

- pkg/helper/docker_center.go
- pkg/helper/docker_center_file_discover.go
- plugins/input/docker/logmeta/metric_container_info.go
This pull request includes changes to the `docker_center.go` and `metric_container_info.go` files to improve the sorting of mount points and clean up redundant code.
Improvements to mount point sorting:
* [`pkg/helper/docker_center.go`](diffhunk://#diff-c485466656194860a9853656d35422aa2df033cf29c41d0da890b567c4df4a72R23): Added a new `sortMounts` function to sort the `Mounts` slice by the `Source` field and invoked this function within the `CreateInfoDetail` method. [[1]](diffhunk://#diff-c485466656194860a9853656d35422aa2df033cf29c41d0da890b567c4df4a72R23) [[2]](diffhunk://#diff-c485466656194860a9853656d35422aa2df033cf29c41d0da890b567c4df4a72R627-R632)
Code cleanup:
* [`plugins/input/docker/logmeta/metric_container_info.go`](diffhunk://#diff-cc624af54a4fb34dd4be36cb3fa5886a0be04d334a34299c …
> fix: container mount path corruption due to concurrent sort in info lookup

- core/plugin/processor/inner/ProcessorSplitMultilineLogStringNative.cpp
- core/plugin/processor/inner/ProcessorSplitMultilineLogStringNative.h
- core/runner/ProcessorRunner.cpp
- core/runner/ProcessorRunner.h
- 问题：上一轮的性能优化中，通过调整boost参数已经实现了极简多行场景，采集速率随处理线程数近线性增加，但是长时间采集下，会出现速率不稳的情况（一会采得快，一会采得慢）。通过火焰图分析，根因是boost::regex对象内部有个shared_ptr成员会在正则匹配的过程中频繁的复制临时变量和析构，shared_ptr在多线程情况下的频繁复制和析够会导致严重的性能问题。
- 解决：boost::regex对象每个线程都复制一份，避免锁竞争。
- 效果：多线程状态下，单个线程的采集速率约为单线程状态的90%（少掉的10%损耗在boost::match_results的频繁析够和构造）
> improve multi thread performance for multiline log split

- core/plugin/flusher/sls/DiskBufferWriter.cpp
- core/plugin/flusher/sls/DiskBufferWriter.h
disk buffer反序列化出来的数据存在问题，导致aliuid变量异常大，导致获取ak失败，并且不断重试，导致内存升高。
触发条件是几个的组合：
1. 进程优雅重启，触发disk buffer write。而流水线中存在大量阻塞流水线和数据，导致写入disk buffer时超时5秒，导致强制停止
2. 对于unauthorized的请求，会重试6个小时
3. disk buffer在发送的时候还会写数据回到disk buffer文件中，可能写坏掉
临时解决方案：判断aliuid大小，如果超出正常长度就跳过
最终解决方案：通过磁盘队列持久化阻塞数据
> fix: skip broken disk buffer

- scripts/plugin_build.sh
Fix compile error when custom GOMODCACHE is set to dir other than $GOPATH/pkg/mod
This pull request includes a small update to the `scripts/plugin_build.sh` file. The change updates the path used to navigate to the `gozstd` module directory, replacing `$(go env GOPATH)/pkg/mod` with `$(go env GOMODCACHE)` to align with modern Go module caching practices.
> compile: use GOMODCACHE instead of GOPATH

- core/ebpf/driver/eBPFDriver.cpp
Fix undefined __wrap_memcpy symbol in eBPFDriver.cpp when COMPATIBLE_MODE is enabled
> fix: resolve undefined __wrap_memcpy symbol in eBPFDriver.cpp when COMPATIBLE_MODE is enabled

- pkg/helper/log_file_reader.go
- pkg/helper/log_file_reader_test.go
问题现象：客户反馈Golang标准输出采集插件在容器停止的时候，末尾的一些数据采集不到
问题原因：容器停止之后，容器标准输出的文件路径就访问不到了，而LogFileReader判断文件是否有变化的时候，依赖文件路径的可访问，因此容器停止之后，未采集的数据就不会继续采集了。
修复方案： LogFileReader判断文件是否有变化的时候，依据当前持有的文件句柄继续判断文件内容，保证继续采集完。（目前会持有60s）
修复前：可以看到最后的数据并没有采集上来
修复后：可以看到最后一行数据采集上来了
> Fixed the issue that the Golang Stdout plugin missed collecting the end of the log file when the container was stopped.

- .github/workflows/benchmark.yaml
- .github/workflows/build-core-ut.yaml
- .github/workflows/build-core.yaml
- .github/workflows/build-pure-plugin.yaml
- .github/workflows/build.yaml
- .github/workflows/e2e-framework.yaml
- .github/workflows/e2e.yaml
- .github/workflows/static-check.yaml
添加了actions-timeline这个步骤，可以把每一步的耗时详细展示出来，便于分析、合并、优化现有的多个workflow
可以看到准备 ubuntu 环境耗时比较久，其次就是 “Build Binary” 和 “Build Docker”，这两步是为了验证能否编译通过，而其他workflow里会重复编译一个结果做测试，所以可以合并起来。result这一步没有用，反而还有额外的等待runner分配的时间。
这个CI由于网络环境问题，“Set up Go”，“Check out code”和“Set custom submodule URL and fetch”都比较久，而且能看到有一次跟 Build 重复的 “Build Binary”，都是可以优化的。
跟Build Core一样的问题。
这个很快，暂时不用优化
可以看到E2E Plugin Framework Test 占用了非常长的时间，实际上它并没有测试用例，就是用github runner编译完了结束，这个是可以优化的。
E2E Behavior Test的时间非常长，其中前半部分是在编译（这个是可以跟其他流程合并的，self-hosted-runner的编译效率高），剩下的 914.39s（15min左右）在串行跑测试，每个测试都需要用docker-compose重复拉镜像、测试、销毁容器的过程，会随着用例的变多，时间越来越长（每个用例在半分钟左右），这里需要改成并行（benchmark已经改好了，不过调研发现并行跑go的测试还有更优的方法，会一并优化掉）
这里的C++ Core Lint、Go Plugin Lint、UnitTest（Go）和UnitTest PluginManager都是可以并行的，改为并行后时间应该在10min内。
该优化方向是基于上文对每个 workflow …
> add actions-timeline

- core/plugin/flusher/sls/FlusherSLS.cpp
问题原因:
weak_ptr expired之后再lock仍然可能获取到空指针
https://stackoverflow.com/questions/37679636/what-is-diffrence-between-lock-and-expired-weak-ptr-c
解决方案：
比较安全的做法是直接lock，然后判断指针是否为空
> Fixed the problem that weak ptr may get a null pointer.

- .github/workflows/benchmark.yaml
- .github/workflows/build-core-ut.yaml
- .github/workflows/build-core.yaml
- .github/workflows/build.yaml
- .github/workflows/e2e-framework.yaml
- .github/workflows/e2e.yaml
- core/ebpf/driver/BPFWrapper.h
The current version of libbpf is too old to recognize new BTF Types in 6.x kernel versions, causing loading failures on newer systems. 
```
[2025-05-13 15:44:14.204906］［debug] ［1301190］/workspaces/loongcollector-enterprise/core/ebpf/EBPFAdapter.cpp: 142 moduLe:eBPFDriver msg:libbpf: Unsupported BTF_KIND:19
[2025-05-13 15:44:14.204914］［debug] ［1301190］/workspaces/loongcollector-enterprise/core/ebpf/EBPFAdapter.cpp: module:eBPFDriver   msg: libbpf: loading kernel BTF '/sys/kernel/btf/vmlinux'：-22
```
This update resolves the "Unsupported BTF_KIND" error and allows proper loading on recent kernels.
> Update libbpf to resolve Unsupported BTF_KIND issue

- pkg/helper/k8smeta/k8s_meta_manager.go
- pkg/helper/k8smeta/k8s_meta_store_interface.go
- plugins/input/kubernetesmetav2/meta_collector.go
- plugins/input/kubernetesmetav2/meta_collector_app.go
- plugins/input/kubernetesmetav2/meta_collector_batch.go
- plugins/input/kubernetesmetav2/meta_collector_core.go
- plugins/input/kubernetesmetav2/meta_collector_storage.go
K8s资源中，这类虽然有默认值的指针，在通过client-go获取时仍然可能是空的。
1. 检查是否是空指针
2. 添加panicRecover，保证至少不crash
> fix: k8s resource nil point

- plugins/input/kubernetesmetav2/meta_collector.go
Pass relationtype to cluster-entity link by entity type
原 ： 对于cluster到Namespace、Node的link的关系类型，默认runs，参数配置没有生效
现 :   基于具体的参数配置（Cluster2Namespace等） 进行关系类型设定
> Update k8s meta with specific relation type

- pkg/logger/logger.go
- plugin_main/plugin_http.go
主要改动：
1. 调试模式下，新增stack信息输出选项，用来输出当前程序堆栈信息
2. 去掉loongcollector logger模块捕获标准输出逻辑
问题原因：
1. seelog内部，在磁盘满的情况下，会使用fmt.Prrint输出日志
4. loongcollector logger模块，会捕获标准输出，然后重定向使用seelog输出
在磁盘满的情况下，loongcollector logger中，捕获标准输出逻辑会hang住，从而导致seelog内部锁一直不释放
关键堆栈信息：
1. seelog内部fmt输出卡住，这里卡住会导致seelog的锁一直被此协程持有，其他协程拿不到锁
2. 业务协程调用seelog卡住
> Fixed the log writing deadlock problem caused by the logical loop of the Golang log module.

- core/collection_pipeline/CollectionPipeline.cpp
- core/collection_pipeline/queue/BoundedProcessQueue.cpp
- core/collection_pipeline/queue/BoundedProcessQueue.h
- core/collection_pipeline/queue/CircularProcessQueue.cpp
- core/collection_pipeline/queue/CircularProcessQueue.h
- core/collection_pipeline/queue/ExactlyOnceQueueManager.cpp
- core/collection_pipeline/queue/ProcessQueueInterface.h
- core/collection_pipeline/queue/ProcessQueueItem.h
- core/collection_pipeline/queue/ProcessQueueManager.cpp
- core/runner/ProcessorRunner.cpp
- core/unittest/pipeline/PipelineUnittest.cpp
- core/unittest/pipeline/PipelineUpdateUnittest.cpp
- core/unittest/plugin/PluginMock.h
- core/unittest/queue/BoundedProcessQueueUnittest.cpp
- core/unittest/queue/CircularProcessQueueUnittest.cpp
- core/unittest/queue/ExactlyOnceQueueManagerUnittest.cpp
- core/unittest/queue/ProcessQueueManagerUnittest.cpp
配置更新时，残留在处理队列中的旧流水线数据，使用新流水线的处理插件处理。但是由于Input可能发生变化，所以退而求其次，使用旧流水线的inputIndex在新流水线找内置处理插件。如果找不到，则跳过内置处理插件。
之前代码在UT中会有非法访问的报错
> fix: processor released before serialized when pipeline update

- pkg/helper/containercenter/container_center.go
- pkg/helper/containercenter/container_center_test.go
问题现象：
非容器场景，但是配置了容器的采集配置，golang模块会持续crash在docker client处
问题原因：
docker client为Interface类型，Go 语言规范规定：
- 接口变量仅当类型和值都为 nil 时才等于 nil
- 当接口持有具体类型的 nil 值时，接口本身不是 nil
修复方案：
initClient失败的时候，强制dc.client = nil，这样保证类型和值都为nil
> Fix the crash caused by interface null value judgment error in golang.

- pkg/helper/containercenter/container_center.go
- pkg/helper/containercenter/container_export.go
- pkg/helper/containercenter/cri_adapter.go
来自真实问题。
loongcollector同节点下的operator挂了，触发了loongcollector的容器发现模块的一个bug：loongcollector在获取这个挂了的容器的元信息时会无限阻塞住，从而导致采集不到后续更新的容器日志（容器发现是一个单独的go协程，里面读写一个cache map维护容器信息。docker/containerd请求与内部读写cache map不是同一个锁，所以也不会造成锁抢占后无限等待恢复，只会导致后续的容器定时发现逻辑卡死，容器信息无法更新）。
```shell
Warning Unhealthy 9m50s (x5970 over 24d) kubelet Liveness probe errored: rpc error: code = Unknown desc = operation timeout: context deadline exceeded
Warning Unhealthy 3m50s (x5971 over 24d) kubelet Readiness probe errored: rpc error: code = Unknown desc = operation timeout: context deadline exceeded
```
pprof堆栈看是卡死在ContainerInspect了。
```shell
1 @ 0x7fc5a83fac96 0x7fc5a840b35c 0x7fc5a8707774 0x7fc5a86faf5a 0x7fc5a86e1e59 0x7fc5a86a1097 0x7fc5a86a08fb 0x7fc5a86a2d3c 0x7fc5a8b1d8aa 0x7fc5a8b1d894 0x7fc5a8b1d513 0x7fc5a8b029ce …
```
> fix: docker inspect timeout

- pkg/models/common.go
- pkg/models/common_test.go
- pkg/models/metrics.go
Change-Id: I976ab23f38e278d44c96def134b73f7af1133ada
原先的实现有点太重了，已经成为metric执行链路上的主要开销
同时优化一下nil KV的内存分配
> optimize: speed up metric get size

- .github/workflows/build-core.yaml
- core/dependencies.cmake
- docker/Dockerfile_build
- docker/Dockerfile_coverage
- docker/Dockerfile_development_part
- docker/Dockerfile_e2e
- docker/Dockerfile_edge_linux
- docs/cn/developer-guide/development-environment.md
- scripts/check_dependencies.sh
grpc find_package会默认优先链接so。但是如果不使用find_package，那么CMake中要手动链接几十个库。
因此，通过设置两个CMake参数，可以让grpc链接静态库。
> fix: grpc find_package link ssl so

- core/file_server/reader/LogFileReader.cpp
- core/file_server/reader/LogFileReader.h
fix #1851
表现为采集loongcollector.LOG，显示为：
> Fix: fix GetConvertedPath error on windows

- core/app_config/AppConfig.cpp
- core/app_config/AppConfig.h
- core/application/Application.cpp
- core/common/EnvUtil.cpp
- core/common/EnvUtil.h
- core/go_pipeline/LogtailPlugin.cpp
- core/plugin/flusher/sls/SLSClientManager.cpp
- core/plugin/processor/inner/ProcessorTagNative.cpp
- core/unittest/app_config/AppConfigUnittest.cpp
- core/unittest/common/CMakeLists.txt
- core/unittest/common/EnvUtilUnittest.cpp
- pkg/flags/flags.go
- pkg/helper/containercenter/container_center.go
- pkg/helper/containercenter/container_center_test.go
- pkg/helper/env_tags.go
- pkg/util/util.go
- pkg/util/util_test.go
This PR introduces a vendor-neutral configuration prefix `LOONG_` as the new standard,  
while maintaining backward compatibility with the existing `ALIYUN_` prefixed  
environment variables and configurations.  
Key changes:  
- Added `LOONG_` prefix as the preferred vendor-neutral option  
- Retained `ALIYUN_` prefix support for backward compatibility  
- Updated documentation to recommend `LOONG_` for new usage  
- Ensured both prefixes function identically  
Examples:
- Setting the LOONG_USER_ID environment variable achieves the same effect as the ALIYUN_LOGTAIL_USER_ID environment variable (retrieving the tenant UID).
- If both LOONG_USER_ID and ALIYUN_LOGTAIL_USER_ID environment variables exist, LOONG_USER_ID takes precedence.
- In a container environment, loong_logs_{configName} …
> support vendor-neutral config prefix (LOONG_) while keeping ALIYUN_ backward compatibility

- README.md
The submodule coolbpf will not be downloaded and compiled following the current **Build and Run** process.
> docs: add '--recurse-submodules' after 'git clone'

- pkg/helper/k8smeta/k8s_meta_deferred_deletion_meta_store.go
- pkg/helper/k8smeta/k8s_meta_deferred_deletion_meta_store_test.go
在k8s 元数据 高频变更场景下（前提 entity数量并无改动），存在内存上涨问题， 问题原因之一在于：每次更新都重建索引，如果索引键没有变化，那么删除和添加的操作是多余的，另外在Update事件中，即使某个索引键的Keys map为空，我们也没有删除它，这可能导致一些空的IndexItem残留，占用内存。
（1）保证实体数不变，触发高频更新事件
（2）对照 内存变化
（3）ai review
> fix: optimize mem  of k8s meta entity
